cask "ana-1000-au" do
  version "latest"
  sha256 :no_check
  url "https://plugins4free.com/get_plug/ANA-1000_Lurker_MacAU.zip"
  name "ANA-1000"
  desc "ANA-1000 is a 2 oscillators analog synthesizer ."
  homepage "https://plugins4free.com/plugin/3022"
  depends_on :macos
  postflight_steps do
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components"
    move "ANA-1000_Lurker_v1.component", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1.component"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/3rd Saws.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/3rd Saws.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/5th Saws.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/5th Saws.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/Abyss.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/Abyss.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/ANA-1000_DEFAULTbank.xmlbank", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/ANA-1000_DEFAULTbank.xmlbank"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/Bass 0.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/Bass 0.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/Bass 1.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/Bass 1.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/Bass 2.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/Bass 2.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/Bass 3.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/Bass 3.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/Bass 4.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/Bass 4.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/Bass 5.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/Bass 5.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/Bass 6.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/Bass 6.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/Bass 7.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/Bass 7.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/Bass 8.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/Bass 8.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/Bass 9.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/Bass 9.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/Cardinal Climber.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/Cardinal Climber.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/Cloudy.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/Cloudy.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/Driftwood.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/Driftwood.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/Electric Piano.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/Electric Piano.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/Equilateral Bass.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/Equilateral Bass.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/Flying Eyes.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/Flying Eyes.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/FX 0.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/FX 0.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/FX 1.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/FX 1.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/FX 2.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/FX 2.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/FX 3.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/FX 3.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/FX 4.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/FX 4.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/FX 5.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/FX 5.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/FX 6.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/FX 6.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/FX 7.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/FX 7.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/FX 8.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/FX 8.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/FX 9.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/FX 9.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/KeeBored.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/KeeBored.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/Lead 1.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/Lead 1.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/Lead 2.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/Lead 2.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/Lead 3.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/Lead 3.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/Lead 4.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/Lead 4.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/Lead 5.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/Lead 5.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/Magi.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/Magi.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/MEGAPAD.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/MEGAPAD.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/Nevaeh.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/Nevaeh.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/Olympus.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/Olympus.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/Sailor.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/Sailor.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/Spooked.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/Spooked.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/Spring.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/Spring.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/Squared.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/Squared.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/SunLight.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/SunLight.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/UnderState.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/UnderState.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/Untune.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/Untune.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/Valhalla.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/Valhalla.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/VLONE.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/VLONE.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/Wavy Bass.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/Wavy Bass.vstpreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets"
    copy "ANA-1000_Lurker_v1 Presets/WideSpread.vstpreset", "{{user}}/Library/Audio/Plug-Ins/Components/ANA-1000_Lurker_v1 Presets/WideSpread.vstpreset"
  end
end
