cask "cheeze-machine-vst" do
  version "latest"
  sha256 :no_check
  url "https://alt1.plugins4free.com/get_plug/CheezeMachine_2007_06_04.dmg"
  name "Cheeze Machine"
  desc "Cheeze Machine emulates the classic string ensemble sound , made popular by such classic synths as the Crumar Performer or the Arp Solina. saw-like waveform chorus ensemble emulator 6-stages phaser reverb"
  homepage "https://plugins4free.com/plugin/285"
  depends_on :macos
  container type: :dmg
  postflight_steps do
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST"
    move "VST/CheezeMachine.vst", "{{user}}/Library/Audio/Plug-Ins/VST/CheezeMachine.vst"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/CheezeMachineMetal.vst"
    copy "VST/CheezeMachineMetal.vst/Icon", "{{user}}/Library/Audio/Plug-Ins/VST/CheezeMachineMetal.vst/Icon"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/CheezeMachineMetal.vst/Contents"
    copy "VST/CheezeMachineMetal.vst/Contents/Info.plist", "{{user}}/Library/Audio/Plug-Ins/VST/CheezeMachineMetal.vst/Contents/Info.plist"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/CheezeMachineMetal.vst/Contents"
    copy "VST/CheezeMachineMetal.vst/Contents/PkgInfo", "{{user}}/Library/Audio/Plug-Ins/VST/CheezeMachineMetal.vst/Contents/PkgInfo"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/CheezeMachineMetal.vst/Contents/MacOS"
    copy "VST/CheezeMachineMetal.vst/Contents/MacOS/CheezeMachineMetal", "{{user}}/Library/Audio/Plug-Ins/VST/CheezeMachineMetal.vst/Contents/MacOS/CheezeMachineMetal"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/CheezeMachineMetal.vst/Contents/Resources"
    copy "VST/CheezeMachineMetal.vst/Contents/Resources/bmp00134.png", "{{user}}/Library/Audio/Plug-Ins/VST/CheezeMachineMetal.vst/Contents/Resources/bmp00134.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/CheezeMachineMetal.vst/Contents/Resources"
    copy "VST/CheezeMachineMetal.vst/Contents/Resources/bmp00145.png", "{{user}}/Library/Audio/Plug-Ins/VST/CheezeMachineMetal.vst/Contents/Resources/bmp00145.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/CheezeMachineMetal.vst/Contents/Resources"
    copy "VST/CheezeMachineMetal.vst/Contents/Resources/bmp00146.png", "{{user}}/Library/Audio/Plug-Ins/VST/CheezeMachineMetal.vst/Contents/Resources/bmp00146.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/CheezeMachineMetal.vst/Contents/Resources"
    copy "VST/CheezeMachineMetal.vst/Contents/Resources/bmp00157.png", "{{user}}/Library/Audio/Plug-Ins/VST/CheezeMachineMetal.vst/Contents/Resources/bmp00157.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/CheezeMachineMetal.vst/Contents/Resources"
    copy "VST/CheezeMachineMetal.vst/Contents/Resources/bmp00158.png", "{{user}}/Library/Audio/Plug-Ins/VST/CheezeMachineMetal.vst/Contents/Resources/bmp00158.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/CheezeMachineMetal.vst/Contents/Resources"
    copy "VST/CheezeMachineMetal.vst/Contents/Resources/bmp00159.png", "{{user}}/Library/Audio/Plug-Ins/VST/CheezeMachineMetal.vst/Contents/Resources/bmp00159.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/CheezeMachineMetal.vst/Contents/Resources"
    copy "VST/CheezeMachineMetal.vst/Contents/Resources/bmp00160.png", "{{user}}/Library/Audio/Plug-Ins/VST/CheezeMachineMetal.vst/Contents/Resources/bmp00160.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/CheezeMachineMetal.vst/Contents/Resources"
    copy "VST/CheezeMachineMetal.vst/Contents/Resources/bmp00161.png", "{{user}}/Library/Audio/Plug-Ins/VST/CheezeMachineMetal.vst/Contents/Resources/bmp00161.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/CheezeMachineMetal.vst/Contents/Resources"
    copy "VST/CheezeMachineMetal.vst/Contents/Resources/bmp00162.png", "{{user}}/Library/Audio/Plug-Ins/VST/CheezeMachineMetal.vst/Contents/Resources/bmp00162.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/CheezeMachineMetal.vst/Contents/Resources"
    copy "VST/CheezeMachineMetal.vst/Contents/Resources/bmp00163.png", "{{user}}/Library/Audio/Plug-Ins/VST/CheezeMachineMetal.vst/Contents/Resources/bmp00163.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/CheezeMachineMetal.vst/Contents/Resources"
    copy "VST/CheezeMachineMetal.vst/Contents/Resources/bmp00164.png", "{{user}}/Library/Audio/Plug-Ins/VST/CheezeMachineMetal.vst/Contents/Resources/bmp00164.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/CheezeMachineMetal.vst/Contents/Resources"
    copy "VST/CheezeMachineMetal.vst/Contents/Resources/bmp00166.png", "{{user}}/Library/Audio/Plug-Ins/VST/CheezeMachineMetal.vst/Contents/Resources/bmp00166.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/CheezeMachineMetal.vst/Contents/Resources"
    copy "VST/CheezeMachineMetal.vst/Contents/Resources/bmp00168.png", "{{user}}/Library/Audio/Plug-Ins/VST/CheezeMachineMetal.vst/Contents/Resources/bmp00168.png"
  end
end
