cask "deep-fry" do
  version "0.3.1"
  sha256 "7ed31b770110168b90e22892fde4a2b184da6bbbf606a4f5a129a737519dccb8"
  url "https://github.com/mitchaiet/deep-fry/releases/download/v0.3.1/Deep-Fry-0.3.1-macOS-universal.zip"
  name "deep-fry"
  desc "Free audio plugin"
  homepage "https://github.com/mitchaiet/deep-fry"
  depends_on :macos
  postflight_steps do
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3"
    move "Deep-Fry-0.3.1-macOS-universal/VST3/Deep Fry.vst3", "{{user}}/Library/Audio/Plug-Ins/VST3/Deep Fry.vst3"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components"
    move "Deep-Fry-0.3.1-macOS-universal/AU/Deep Fry.component", "{{user}}/Library/Audio/Plug-Ins/Components/Deep Fry.component"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal"
    copy "Deep-Fry-0.3.1-macOS-universal/Install.command", "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/Install.command"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal"
    copy "Deep-Fry-0.3.1-macOS-universal/LICENSE", "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/LICENSE"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/LICENSES"
    copy "Deep-Fry-0.3.1-macOS-universal/LICENSES/SOURCE-MANIFEST.json", "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/LICENSES/SOURCE-MANIFEST.json"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/LICENSES"
    copy "Deep-Fry-0.3.1-macOS-universal/LICENSES/AudioUnitSDK-COPYRIGHT-NOTICES.txt", "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/LICENSES/AudioUnitSDK-COPYRIGHT-NOTICES.txt"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/LICENSES"
    copy "Deep-Fry-0.3.1-macOS-universal/LICENSES/PNG-LICENSE.txt", "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/LICENSES/PNG-LICENSE.txt"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/LICENSES"
    copy "Deep-Fry-0.3.1-macOS-universal/LICENSES/AudioUnitSDK-LICENSE.txt", "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/LICENSES/AudioUnitSDK-LICENSE.txt"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/LICENSES"
    copy "Deep-Fry-0.3.1-macOS-universal/LICENSES/VST3-LICENSE.txt", "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/LICENSES/VST3-LICENSE.txt"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/LICENSES"
    copy "Deep-Fry-0.3.1-macOS-universal/LICENSES/FLAC-LICENSE.txt", "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/LICENSES/FLAC-LICENSE.txt"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/LICENSES"
    copy "Deep-Fry-0.3.1-macOS-universal/LICENSES/JUCE-LICENSE.md", "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/LICENSES/JUCE-LICENSE.md"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/LICENSES"
    copy "Deep-Fry-0.3.1-macOS-universal/LICENSES/Windows-MSVC-SOURCE-MANIFEST.json", "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/LICENSES/Windows-MSVC-SOURCE-MANIFEST.json"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/LICENSES"
    copy "Deep-Fry-0.3.1-macOS-universal/LICENSES/Windows-MSVC-STL-LICENSE.txt", "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/LICENSES/Windows-MSVC-STL-LICENSE.txt"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/LICENSES"
    copy "Deep-Fry-0.3.1-macOS-universal/LICENSES/Windows-MSVC-STL-NOTICE.txt", "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/LICENSES/Windows-MSVC-STL-NOTICE.txt"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/LICENSES"
    copy "Deep-Fry-0.3.1-macOS-universal/LICENSES/SheenBidi-LICENSE.txt", "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/LICENSES/SheenBidi-LICENSE.txt"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/LICENSES"
    copy "Deep-Fry-0.3.1-macOS-universal/LICENSES/JUCE-MODULE-NOTICE.txt", "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/LICENSES/JUCE-MODULE-NOTICE.txt"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/LICENSES"
    copy "Deep-Fry-0.3.1-macOS-universal/LICENSES/HarfBuzz-SOURCE-NOTICES.txt", "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/LICENSES/HarfBuzz-SOURCE-NOTICES.txt"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/LICENSES"
    copy "Deep-Fry-0.3.1-macOS-universal/LICENSES/IJG-JPEG-README.txt", "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/LICENSES/IJG-JPEG-README.txt"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/LICENSES"
    copy "Deep-Fry-0.3.1-macOS-universal/LICENSES/IBM-Plex-OFL.txt", "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/LICENSES/IBM-Plex-OFL.txt"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/LICENSES"
    copy "Deep-Fry-0.3.1-macOS-universal/LICENSES/Ogg-Vorbis-LICENSE.txt", "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/LICENSES/Ogg-Vorbis-LICENSE.txt"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/LICENSES"
    copy "Deep-Fry-0.3.1-macOS-universal/LICENSES/Vorbis-COPYING.txt", "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/LICENSES/Vorbis-COPYING.txt"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/LICENSES"
    copy "Deep-Fry-0.3.1-macOS-universal/LICENSES/Ogg-Vorbis-SOURCE-NOTICES.txt", "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/LICENSES/Ogg-Vorbis-SOURCE-NOTICES.txt"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/LICENSES"
    copy "Deep-Fry-0.3.1-macOS-universal/LICENSES/HarfBuzz-COPYING.txt", "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/LICENSES/HarfBuzz-COPYING.txt"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/LICENSES"
    copy "Deep-Fry-0.3.1-macOS-universal/LICENSES/SheenBidi-SOURCE-NOTICES.txt", "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/LICENSES/SheenBidi-SOURCE-NOTICES.txt"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/LICENSES"
    copy "Deep-Fry-0.3.1-macOS-universal/LICENSES/VST3-ADDITIONAL-NOTICES.txt", "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/LICENSES/VST3-ADDITIONAL-NOTICES.txt"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/LICENSES"
    copy "Deep-Fry-0.3.1-macOS-universal/LICENSES/zlib-LICENSE.txt", "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/LICENSES/zlib-LICENSE.txt"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal"
    copy "Deep-Fry-0.3.1-macOS-universal/CHANGELOG.md", "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/CHANGELOG.md"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/Standalone/Deep Fry.app/Contents/_CodeSignature"
    copy "Deep-Fry-0.3.1-macOS-universal/Standalone/Deep Fry.app/Contents/_CodeSignature/CodeResources", "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/Standalone/Deep Fry.app/Contents/_CodeSignature/CodeResources"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/Standalone/Deep Fry.app/Contents/MacOS"
    copy "Deep-Fry-0.3.1-macOS-universal/Standalone/Deep Fry.app/Contents/MacOS/Deep Fry", "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/Standalone/Deep Fry.app/Contents/MacOS/Deep Fry"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/Standalone/Deep Fry.app/Contents/Resources"
    copy "Deep-Fry-0.3.1-macOS-universal/Standalone/Deep Fry.app/Contents/Resources/RecentFilesMenuTemplate.nib", "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/Standalone/Deep Fry.app/Contents/Resources/RecentFilesMenuTemplate.nib"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/Standalone/Deep Fry.app/Contents"
    copy "Deep-Fry-0.3.1-macOS-universal/Standalone/Deep Fry.app/Contents/Info.plist", "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/Standalone/Deep Fry.app/Contents/Info.plist"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/Standalone/Deep Fry.app/Contents"
    copy "Deep-Fry-0.3.1-macOS-universal/Standalone/Deep Fry.app/Contents/PkgInfo", "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/Standalone/Deep Fry.app/Contents/PkgInfo"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal"
    copy "Deep-Fry-0.3.1-macOS-universal/THIRD_PARTY_NOTICES.md", "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/THIRD_PARTY_NOTICES.md"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal"
    copy "Deep-Fry-0.3.1-macOS-universal/RELEASE-MANIFEST.json", "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/RELEASE-MANIFEST.json"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal"
    copy "Deep-Fry-0.3.1-macOS-universal/README.txt", "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/README.txt"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal"
    copy "Deep-Fry-0.3.1-macOS-universal/COPYRIGHT", "{{user}}/Library/Audio/Plug-Ins/Resources/Deep-Fry-0.3.1-macOS-universal/COPYRIGHT"
  end
end
