cask "deepfilternet3" do
  version "0.7.0"
  sha256 "0589d9e42dd6532c45adfe6d519ec36229a80c1315f40aa847ea4b37958969a4"
  url "https://github.com/Shuichi346/DeepFilterNet3-VST3/releases/download/v0.7.0/DeepFilterNR-v0.7.0-macos-arm64.zip"
  name "DeepFilterNet3"
  desc "Free audio plugin"
  homepage "https://github.com/Shuichi346/DeepFilterNet3-VST3"
  depends_on :macos
  postflight_steps do
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/CLAP"
    move "DeepFilterNR-v0.7.0-macos-arm64/Plugins/deepfilter-vst.clap", "{{user}}/Library/Audio/Plug-Ins/CLAP/deepfilter-vst.clap"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3"
    move "DeepFilterNR-v0.7.0-macos-arm64/Plugins/deepfilter-vst.vst3", "{{user}}/Library/Audio/Plug-Ins/VST3/deepfilter-vst.vst3"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Resources/DeepFilterNR-v0.7.0-macos-arm64"
    copy "DeepFilterNR-v0.7.0-macos-arm64/RELEASE_INFO.txt", "{{user}}/Library/Audio/Plug-Ins/Resources/DeepFilterNR-v0.7.0-macos-arm64/RELEASE_INFO.txt"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Resources/DeepFilterNR-v0.7.0-macos-arm64"
    copy "DeepFilterNR-v0.7.0-macos-arm64/LICENSE", "{{user}}/Library/Audio/Plug-Ins/Resources/DeepFilterNR-v0.7.0-macos-arm64/LICENSE"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Resources/DeepFilterNR-v0.7.0-macos-arm64"
    copy "DeepFilterNR-v0.7.0-macos-arm64/BINARY_SHA256SUMS.txt", "{{user}}/Library/Audio/Plug-Ins/Resources/DeepFilterNR-v0.7.0-macos-arm64/BINARY_SHA256SUMS.txt"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Resources/DeepFilterNR-v0.7.0-macos-arm64"
    copy "DeepFilterNR-v0.7.0-macos-arm64/THIRD_PARTY_NOTICES.md", "{{user}}/Library/Audio/Plug-Ins/Resources/DeepFilterNR-v0.7.0-macos-arm64/THIRD_PARTY_NOTICES.md"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Resources/DeepFilterNR-v0.7.0-macos-arm64"
    copy "DeepFilterNR-v0.7.0-macos-arm64/README.md", "{{user}}/Library/Audio/Plug-Ins/Resources/DeepFilterNR-v0.7.0-macos-arm64/README.md"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Resources/DeepFilterNR-v0.7.0-macos-arm64/Third-Party-Licenses"
    copy "DeepFilterNR-v0.7.0-macos-arm64/Third-Party-Licenses/Unicode-3.0.txt", "{{user}}/Library/Audio/Plug-Ins/Resources/DeepFilterNR-v0.7.0-macos-arm64/Third-Party-Licenses/Unicode-3.0.txt"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Resources/DeepFilterNR-v0.7.0-macos-arm64/Third-Party-Licenses"
    copy "DeepFilterNR-v0.7.0-macos-arm64/Third-Party-Licenses/Embedded-Font-Licenses.txt", "{{user}}/Library/Audio/Plug-Ins/Resources/DeepFilterNR-v0.7.0-macos-arm64/Third-Party-Licenses/Embedded-Font-Licenses.txt"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Resources/DeepFilterNR-v0.7.0-macos-arm64/Third-Party-Licenses"
    copy "DeepFilterNR-v0.7.0-macos-arm64/Third-Party-Licenses/Apache-2.0.txt", "{{user}}/Library/Audio/Plug-Ins/Resources/DeepFilterNR-v0.7.0-macos-arm64/Third-Party-Licenses/Apache-2.0.txt"
  end
end
