cask "emulator-i-au" do
  version "latest"
  sha256 :no_check
  url "https://alt1.plugins4free.com/get_plug/Emulator-I_MacAU.zip"
  name "Emulator I"
  desc "Emulator I is a rompler featuring the famous E-mu sampler soundbank ."
  homepage "https://plugins4free.com/plugin/2970"
  depends_on :macos
  postflight_steps do
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components"
    move "Emulator I Mac AU/Emulator I.component", "{{user}}/Library/Audio/Plug-Ins/Components/Emulator I.component"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Emulator I Presets"
    copy "Emulator I Mac AU/Emulator I Presets/Add_reverb.aupreset", "{{user}}/Library/Audio/Plug-Ins/Components/Emulator I Presets/Add_reverb.aupreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Emulator I Presets"
    copy "Emulator I Mac AU/Emulator I Presets/Copy_10_Patch___1.aupreset", "{{user}}/Library/Audio/Plug-Ins/Components/Emulator I Presets/Copy_10_Patch___1.aupreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Emulator I Presets"
    copy "Emulator I Mac AU/Emulator I Presets/Copy_11_Patch___1.aupreset", "{{user}}/Library/Audio/Plug-Ins/Components/Emulator I Presets/Copy_11_Patch___1.aupreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Emulator I Presets"
    copy "Emulator I Mac AU/Emulator I Presets/Copy_12_Patch___1.aupreset", "{{user}}/Library/Audio/Plug-Ins/Components/Emulator I Presets/Copy_12_Patch___1.aupreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Emulator I Presets"
    copy "Emulator I Mac AU/Emulator I Presets/Copy_13_Patch___1.aupreset", "{{user}}/Library/Audio/Plug-Ins/Components/Emulator I Presets/Copy_13_Patch___1.aupreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Emulator I Presets"
    copy "Emulator I Mac AU/Emulator I Presets/Copy_14_Patch___1.aupreset", "{{user}}/Library/Audio/Plug-Ins/Components/Emulator I Presets/Copy_14_Patch___1.aupreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Emulator I Presets"
    copy "Emulator I Mac AU/Emulator I Presets/Copy_15_Patch___1.aupreset", "{{user}}/Library/Audio/Plug-Ins/Components/Emulator I Presets/Copy_15_Patch___1.aupreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Emulator I Presets"
    copy "Emulator I Mac AU/Emulator I Presets/Copy_8_Patch___1.aupreset", "{{user}}/Library/Audio/Plug-Ins/Components/Emulator I Presets/Copy_8_Patch___1.aupreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Emulator I Presets"
    copy "Emulator I Mac AU/Emulator I Presets/Copy_9_Patch___1.aupreset", "{{user}}/Library/Audio/Plug-Ins/Components/Emulator I Presets/Copy_9_Patch___1.aupreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Emulator I Presets"
    copy "Emulator I Mac AU/Emulator I Presets/Filter_Piano.aupreset", "{{user}}/Library/Audio/Plug-Ins/Components/Emulator I Presets/Filter_Piano.aupreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Emulator I Presets"
    copy "Emulator I Mac AU/Emulator I Presets/Init_Sound.aupreset", "{{user}}/Library/Audio/Plug-Ins/Components/Emulator I Presets/Init_Sound.aupreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Emulator I Presets"
    copy "Emulator I Mac AU/Emulator I Presets/Moving_Drums.aupreset", "{{user}}/Library/Audio/Plug-Ins/Components/Emulator I Presets/Moving_Drums.aupreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Emulator I Presets"
    copy "Emulator I Mac AU/Emulator I Presets/Slow_Pad.aupreset", "{{user}}/Library/Audio/Plug-Ins/Components/Emulator I Presets/Slow_Pad.aupreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Emulator I Presets"
    copy "Emulator I Mac AU/Emulator I Presets/Strange_Love_Voices.aupreset", "{{user}}/Library/Audio/Plug-Ins/Components/Emulator I Presets/Strange_Love_Voices.aupreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Emulator I Presets"
    copy "Emulator I Mac AU/Emulator I Presets/Synclavier.aupreset", "{{user}}/Library/Audio/Plug-Ins/Components/Emulator I Presets/Synclavier.aupreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Emulator I Presets"
    copy "Emulator I Mac AU/Emulator I Presets/Wurli.aupreset", "{{user}}/Library/Audio/Plug-Ins/Components/Emulator I Presets/Wurli.aupreset"
  end
end
