cask "fogpad" do
  version "1.0.3"
  sha256 "206bfe64ea8b26067f3d550d24ba6e93f5550c1f588e92c2b3d3128c8ba1dc0a"
  url "https://github.com/igorski/fogpad/releases/download/1.0.3/fogpad.1.0.3_macos.zip"
  name "fogpad"
  desc "Free audio plugin"
  homepage "https://github.com/igorski/fogpad"
  depends_on :macos
  postflight_steps do
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3"
    move "AU/Fogpad AUV3.app/Contents/PlugIns/auv3.appex/Contents/PlugIns/plugin.vst3", "{{user}}/Library/Audio/Plug-Ins/VST3/plugin.vst3"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST"
    move "VST/fogpad.vst", "{{user}}/Library/Audio/Plug-Ins/VST/fogpad.vst"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3"
    move "VST3/fogpad.vst3", "{{user}}/Library/Audio/Plug-Ins/VST3/fogpad.vst3"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Fogpad AUV3.app/Contents"
    copy "AU/Fogpad AUV3.app/Contents/CodeResources", "{{user}}/Library/Audio/Plug-Ins/Components/Fogpad AUV3.app/Contents/CodeResources"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Fogpad AUV3.app/Contents"
    copy "AU/Fogpad AUV3.app/Contents/Info.plist", "{{user}}/Library/Audio/Plug-Ins/Components/Fogpad AUV3.app/Contents/Info.plist"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Fogpad AUV3.app/Contents"
    copy "AU/Fogpad AUV3.app/Contents/PkgInfo", "{{user}}/Library/Audio/Plug-Ins/Components/Fogpad AUV3.app/Contents/PkgInfo"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Fogpad AUV3.app/Contents/_CodeSignature"
    copy "AU/Fogpad AUV3.app/Contents/_CodeSignature/CodeResources", "{{user}}/Library/Audio/Plug-Ins/Components/Fogpad AUV3.app/Contents/_CodeSignature/CodeResources"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Fogpad AUV3.app/Contents/MacOS"
    copy "AU/Fogpad AUV3.app/Contents/MacOS/Fogpad AUV3", "{{user}}/Library/Audio/Plug-Ins/Components/Fogpad AUV3.app/Contents/MacOS/Fogpad AUV3"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Fogpad AUV3.app/Contents/Resources"
    copy "AU/Fogpad AUV3.app/Contents/Resources/loop.wav", "{{user}}/Library/Audio/Plug-Ins/Components/Fogpad AUV3.app/Contents/Resources/loop.wav"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Fogpad AUV3.app/Contents/Resources"
    copy "AU/Fogpad AUV3.app/Contents/Resources/plugin.icns", "{{user}}/Library/Audio/Plug-Ins/Components/Fogpad AUV3.app/Contents/Resources/plugin.icns"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Fogpad AUV3.app/Contents/Resources/Main.storyboardc"
    copy "AU/Fogpad AUV3.app/Contents/Resources/Main.storyboardc/MainMenu.nib", "{{user}}/Library/Audio/Plug-Ins/Components/Fogpad AUV3.app/Contents/Resources/Main.storyboardc/MainMenu.nib"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Fogpad AUV3.app/Contents/Resources/Main.storyboardc"
    copy "AU/Fogpad AUV3.app/Contents/Resources/Main.storyboardc/XfG-lQ-9wD-view-m2S-Jp-Qdl.nib", "{{user}}/Library/Audio/Plug-Ins/Components/Fogpad AUV3.app/Contents/Resources/Main.storyboardc/XfG-lQ-9wD-view-m2S-Jp-Qdl.nib"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Fogpad AUV3.app/Contents/Resources/Main.storyboardc"
    copy "AU/Fogpad AUV3.app/Contents/Resources/Main.storyboardc/NSWindowController-B8D-0N-5wS.nib", "{{user}}/Library/Audio/Plug-Ins/Components/Fogpad AUV3.app/Contents/Resources/Main.storyboardc/NSWindowController-B8D-0N-5wS.nib"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Fogpad AUV3.app/Contents/Resources/Main.storyboardc"
    copy "AU/Fogpad AUV3.app/Contents/Resources/Main.storyboardc/Info.plist", "{{user}}/Library/Audio/Plug-Ins/Components/Fogpad AUV3.app/Contents/Resources/Main.storyboardc/Info.plist"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Fogpad AUV3.app/Contents/PlugIns/auv3.appex/Contents"
    copy "AU/Fogpad AUV3.app/Contents/PlugIns/auv3.appex/Contents/Info.plist", "{{user}}/Library/Audio/Plug-Ins/Components/Fogpad AUV3.app/Contents/PlugIns/auv3.appex/Contents/Info.plist"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Fogpad AUV3.app/Contents/PlugIns/auv3.appex/Contents/_CodeSignature"
    copy "AU/Fogpad AUV3.app/Contents/PlugIns/auv3.appex/Contents/_CodeSignature/CodeResources", "{{user}}/Library/Audio/Plug-Ins/Components/Fogpad AUV3.app/Contents/PlugIns/auv3.appex/Contents/_CodeSignature/CodeResources"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Fogpad AUV3.app/Contents/PlugIns/auv3.appex/Contents/MacOS"
    copy "AU/Fogpad AUV3.app/Contents/PlugIns/auv3.appex/Contents/MacOS/fogpad_auv3_appextension_macos", "{{user}}/Library/Audio/Plug-Ins/Components/Fogpad AUV3.app/Contents/PlugIns/auv3.appex/Contents/MacOS/fogpad_auv3_appextension_macos"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Resources"
    copy "README.txt", "{{user}}/Library/Audio/Plug-Ins/Resources/README.txt"
  end
end
