cask "gatewaystereoplus" do
  version "1.0.0"
  sha256 "b04149d3464361dedf482406c8e5706baeb2fc8cbb80aec1cc30911720c2319e"
  url "https://github.com/Naaxas/GatewayStereoPlus/releases/download/v1.0.0/GatewayStereoPlus-1.0.0-macOS-arm64.zip"
  name "GatewayStereoPlus"
  desc "Free audio plugin"
  homepage "https://github.com/Naaxas/GatewayStereoPlus"
  depends_on :macos
  postflight_steps do
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3"
    move "GatewayStereoPlus-macOS-arm64/GatewayStereoPlus.vst3", "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.vst3"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3"
    copy "GatewayStereoPlus-macOS-arm64/Gateway-Stereo-Plus-Manual.html", "{{user}}/Library/Audio/Plug-Ins/VST3/Gateway-Stereo-Plus-Manual.html"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3"
    copy "GatewayStereoPlus-macOS-arm64/install-macos.command", "{{user}}/Library/Audio/Plug-Ins/VST3/install-macos.command"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3"
    copy "GatewayStereoPlus-macOS-arm64/LICENSE", "{{user}}/Library/Audio/Plug-Ins/VST3/LICENSE"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3"
    copy "GatewayStereoPlus-macOS-arm64/CHANGELOG.md", "{{user}}/Library/Audio/Plug-Ins/VST3/CHANGELOG.md"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3/images"
    copy "GatewayStereoPlus-macOS-arm64/images/plugin-bar-meters.png", "{{user}}/Library/Audio/Plug-Ins/VST3/images/plugin-bar-meters.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3/images"
    copy "GatewayStereoPlus-macOS-arm64/images/plugin-vu-meters.png", "{{user}}/Library/Audio/Plug-Ins/VST3/images/plugin-vu-meters.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3"
    copy "GatewayStereoPlus-macOS-arm64/README.md", "{{user}}/Library/Audio/Plug-Ins/VST3/README.md"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3"
    copy "GatewayStereoPlus-macOS-arm64/KNOWN_ISSUES.md", "{{user}}/Library/Audio/Plug-Ins/VST3/KNOWN_ISSUES.md"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/_CodeSignature"
    copy "GatewayStereoPlus-macOS-arm64/GatewayStereoPlus.component/Contents/_CodeSignature/CodeResources", "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/_CodeSignature/CodeResources"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/MacOS"
    copy "GatewayStereoPlus-macOS-arm64/GatewayStereoPlus.component/Contents/MacOS/GatewayStereoPlus", "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/MacOS/GatewayStereoPlus"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources"
    copy "GatewayStereoPlus-macOS-arm64/GatewayStereoPlus.component/Contents/Resources/Lines@3x.png", "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources/Lines@3x.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources"
    copy "GatewayStereoPlus-macOS-arm64/GatewayStereoPlus.component/Contents/Resources/Lines.png", "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources/Lines.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources"
    copy "GatewayStereoPlus-macOS-arm64/GatewayStereoPlus.component/Contents/Resources/ThirdPartyNotices.txt", "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources/ThirdPartyNotices.txt"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources"
    copy "GatewayStereoPlus-macOS-arm64/GatewayStereoPlus.component/Contents/Resources/Lines@2x.png", "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources/Lines@2x.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources"
    copy "GatewayStereoPlus-macOS-arm64/GatewayStereoPlus.component/Contents/Resources/File.svg", "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources/File.svg"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources"
    copy "GatewayStereoPlus-macOS-arm64/GatewayStereoPlus.component/Contents/Resources/Roboto-Regular.ttf", "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources/Roboto-Regular.ttf"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources"
    copy "GatewayStereoPlus-macOS-arm64/GatewayStereoPlus.component/Contents/Resources/ArrowRight.svg", "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources/ArrowRight.svg"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources"
    copy "GatewayStereoPlus-macOS-arm64/GatewayStereoPlus.component/Contents/Resources/SlideSwitchHandle.png", "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources/SlideSwitchHandle.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources"
    copy "GatewayStereoPlus-macOS-arm64/GatewayStereoPlus.component/Contents/Resources/FileBackground.png", "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources/FileBackground.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources"
    copy "GatewayStereoPlus-macOS-arm64/GatewayStereoPlus.component/Contents/Resources/MeterBackground.png", "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources/MeterBackground.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources"
    copy "GatewayStereoPlus-macOS-arm64/GatewayStereoPlus.component/Contents/Resources/Background.jpg", "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources/Background.jpg"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources"
    copy "GatewayStereoPlus-macOS-arm64/GatewayStereoPlus.component/Contents/Resources/Gear.svg", "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources/Gear.svg"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources"
    copy "GatewayStereoPlus-macOS-arm64/GatewayStereoPlus.component/Contents/Resources/FileBackground@2x.png", "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources/FileBackground@2x.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources"
    copy "GatewayStereoPlus-macOS-arm64/GatewayStereoPlus.component/Contents/Resources/KnobBackground.png", "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources/KnobBackground.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources"
    copy "GatewayStereoPlus-macOS-arm64/GatewayStereoPlus.component/Contents/Resources/InputLevelBackground@2x.png", "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources/InputLevelBackground@2x.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources"
    copy "GatewayStereoPlus-macOS-arm64/GatewayStereoPlus.component/Contents/Resources/IRIconOn.svg", "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources/IRIconOn.svg"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources"
    copy "GatewayStereoPlus-macOS-arm64/GatewayStereoPlus.component/Contents/Resources/InputLevelBackground@3x.png", "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources/InputLevelBackground@3x.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources"
    copy "GatewayStereoPlus-macOS-arm64/GatewayStereoPlus.component/Contents/Resources/Michroma-Regular.ttf", "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources/Michroma-Regular.ttf"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources"
    copy "GatewayStereoPlus-macOS-arm64/GatewayStereoPlus.component/Contents/Resources/FileBackground@3x.png", "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources/FileBackground@3x.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources"
    copy "GatewayStereoPlus-macOS-arm64/GatewayStereoPlus.component/Contents/Resources/MeterBackground@3x.png", "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources/MeterBackground@3x.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources"
    copy "GatewayStereoPlus-macOS-arm64/GatewayStereoPlus.component/Contents/Resources/SlimmableIcon.svg", "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources/SlimmableIcon.svg"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources"
    copy "GatewayStereoPlus-macOS-arm64/GatewayStereoPlus.component/Contents/Resources/Background@2x.jpg", "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources/Background@2x.jpg"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources"
    copy "GatewayStereoPlus-macOS-arm64/GatewayStereoPlus.component/Contents/Resources/KnobBackground@3x.png", "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources/KnobBackground@3x.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources"
    copy "GatewayStereoPlus-macOS-arm64/GatewayStereoPlus.component/Contents/Resources/Globe.svg", "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources/Globe.svg"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources"
    copy "GatewayStereoPlus-macOS-arm64/GatewayStereoPlus.component/Contents/Resources/Cross.svg", "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources/Cross.svg"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources"
    copy "GatewayStereoPlus-macOS-arm64/GatewayStereoPlus.component/Contents/Resources/SlideSwitchHandle@2x.png", "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources/SlideSwitchHandle@2x.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources"
    copy "GatewayStereoPlus-macOS-arm64/GatewayStereoPlus.component/Contents/Resources/SlideSwitchHandle@3x.png", "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources/SlideSwitchHandle@3x.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources"
    copy "GatewayStereoPlus-macOS-arm64/GatewayStereoPlus.component/Contents/Resources/ArrowLeft.svg", "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources/ArrowLeft.svg"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources"
    copy "GatewayStereoPlus-macOS-arm64/GatewayStereoPlus.component/Contents/Resources/ModelIcon.svg", "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources/ModelIcon.svg"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources"
    copy "GatewayStereoPlus-macOS-arm64/GatewayStereoPlus.component/Contents/Resources/KnobBackground@2x.png", "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources/KnobBackground@2x.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources"
    copy "GatewayStereoPlus-macOS-arm64/GatewayStereoPlus.component/Contents/Resources/Background@3x.jpg", "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources/Background@3x.jpg"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources"
    copy "GatewayStereoPlus-macOS-arm64/GatewayStereoPlus.component/Contents/Resources/IRIconOff.svg", "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources/IRIconOff.svg"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources"
    copy "GatewayStereoPlus-macOS-arm64/GatewayStereoPlus.component/Contents/Resources/MeterBackground@2x.png", "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources/MeterBackground@2x.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources"
    copy "GatewayStereoPlus-macOS-arm64/GatewayStereoPlus.component/Contents/Resources/InputLevelBackground.png", "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources/InputLevelBackground.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources"
    copy "GatewayStereoPlus-macOS-arm64/GatewayStereoPlus.component/Contents/Resources/GatewayStereoPlus.rsrc", "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Resources/GatewayStereoPlus.rsrc"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents"
    copy "GatewayStereoPlus-macOS-arm64/GatewayStereoPlus.component/Contents/Info.plist", "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/Info.plist"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents"
    copy "GatewayStereoPlus-macOS-arm64/GatewayStereoPlus.component/Contents/PkgInfo", "{{user}}/Library/Audio/Plug-Ins/VST3/GatewayStereoPlus.component/Contents/PkgInfo"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3"
    copy "GatewayStereoPlus-macOS-arm64/README-INSTALL.txt", "{{user}}/Library/Audio/Plug-Ins/VST3/README-INSTALL.txt"
  end
end
