cask "harsh-digital-nose-vst" do
  version "latest"
  sha256 :no_check
  url "https://alt1.plugins4free.com/get_plug/HarshDigitalNose.dmg"
  name "Harsh Digital Nose"
  desc "Harsh Digital Nose converts 2 images into 2 oscillator waveforms and then mixes them in various horrible ways."
  homepage "https://plugins4free.com/plugin/703"
  depends_on :macos
  container type: :dmg
  postflight_steps do
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST"
    move "Harsh Digital Nose.vst", "{{user}}/Library/Audio/Plug-Ins/VST/Harsh Digital Nose.vst"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/.fseventsd"
    copy ".fseventsd/00000000002efc5c", "{{user}}/Library/Audio/Plug-Ins/VST/.fseventsd/00000000002efc5c"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/.fseventsd"
    copy ".fseventsd/00000000002efc5d", "{{user}}/Library/Audio/Plug-Ins/VST/.fseventsd/00000000002efc5d"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/.fseventsd"
    copy ".fseventsd/00000000002efc5e", "{{user}}/Library/Audio/Plug-Ins/VST/.fseventsd/00000000002efc5e"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/.fseventsd"
    copy ".fseventsd/00000000002efc5f", "{{user}}/Library/Audio/Plug-Ins/VST/.fseventsd/00000000002efc5f"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/.fseventsd"
    copy ".fseventsd/00000000002f1aff", "{{user}}/Library/Audio/Plug-Ins/VST/.fseventsd/00000000002f1aff"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/.fseventsd"
    copy ".fseventsd/00000000002f1b00", "{{user}}/Library/Audio/Plug-Ins/VST/.fseventsd/00000000002f1b00"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/.fseventsd"
    copy ".fseventsd/00000000002f1c30", "{{user}}/Library/Audio/Plug-Ins/VST/.fseventsd/00000000002f1c30"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/.fseventsd"
    copy ".fseventsd/00000000002f1c31", "{{user}}/Library/Audio/Plug-Ins/VST/.fseventsd/00000000002f1c31"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/.fseventsd"
    copy ".fseventsd/00000000002fa8cf", "{{user}}/Library/Audio/Plug-Ins/VST/.fseventsd/00000000002fa8cf"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/.fseventsd"
    copy ".fseventsd/00000000002fa8d0", "{{user}}/Library/Audio/Plug-Ins/VST/.fseventsd/00000000002fa8d0"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/.fseventsd"
    copy ".fseventsd/00000000003153e5", "{{user}}/Library/Audio/Plug-Ins/VST/.fseventsd/00000000003153e5"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/.fseventsd"
    copy ".fseventsd/00000000003153e6", "{{user}}/Library/Audio/Plug-Ins/VST/.fseventsd/00000000003153e6"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/.fseventsd"
    copy ".fseventsd/fseventsd-uuid", "{{user}}/Library/Audio/Plug-Ins/VST/.fseventsd/fseventsd-uuid"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Harsh Digital Nose.component/Contents"
    copy "Harsh Digital Nose.component/Contents/Info.plist", "{{user}}/Library/Audio/Plug-Ins/VST/Harsh Digital Nose.component/Contents/Info.plist"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Harsh Digital Nose.component/Contents"
    copy "Harsh Digital Nose.component/Contents/PkgInfo", "{{user}}/Library/Audio/Plug-Ins/VST/Harsh Digital Nose.component/Contents/PkgInfo"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Harsh Digital Nose.component/Contents/MacOS"
    copy "Harsh Digital Nose.component/Contents/MacOS/Harsh Digital Nose", "{{user}}/Library/Audio/Plug-Ins/VST/Harsh Digital Nose.component/Contents/MacOS/Harsh Digital Nose"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Harsh Digital Nose.component/Contents/Resources"
    copy "Harsh Digital Nose.component/Contents/Resources/Harsh Digital Nose.rsrc", "{{user}}/Library/Audio/Plug-Ins/VST/Harsh Digital Nose.component/Contents/Resources/Harsh Digital Nose.rsrc"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages"
    copy "HDNImages/Cube_grd_src.png", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Cube_grd_src.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages"
    copy "HDNImages/Cube_pixit_grd.png", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Cube_pixit_grd.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages"
    copy "HDNImages/Cube_pixit_grd2.png", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Cube_pixit_grd2.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages"
    copy "HDNImages/Cube_sk1.png", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Cube_sk1.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages"
    copy "HDNImages/Cube_sk2_grey.png", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Cube_sk2_grey.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages"
    copy "HDNImages/Cube_sk3.png", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Cube_sk3.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages"
    copy "HDNImages/HDN_cube.png", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/HDN_cube.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages"
    copy "HDNImages/HDN_grid.png", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/HDN_grid.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages"
    copy "HDNImages/invsine.png", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/invsine.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages"
    copy "HDNImages/leonard.png", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/leonard.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages"
    copy "HDNImages/lightningbolt2.png", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/lightningbolt2.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages"
    copy "HDNImages/lines2_xmp.png", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/lines2_xmp.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages"
    copy "HDNImages/lines_Trc.png", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/lines_Trc.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages"
    copy "HDNImages/lines_xmp_msk.png", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/lines_xmp_msk.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages"
    copy "HDNImages/loop test.wav.png", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/loop test.wav.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages"
    copy "HDNImages/mtg_b_red.png", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/mtg_b_red.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages"
    copy "HDNImages/mtg_c_red.png", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/mtg_c_red.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages"
    copy "HDNImages/mtg_grid-b_red.png", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/mtg_grid-b_red.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages"
    copy "HDNImages/mtg_grid-c_red.png", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/mtg_grid-c_red.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages"
    copy "HDNImages/mtg_grid_red.png", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/mtg_grid_red.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages"
    copy "HDNImages/mtg_src_red.png", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/mtg_src_red.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages"
    copy "HDNImages/noise.png", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/noise.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages"
    copy "HDNImages/noise2.png", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/noise2.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages"
    copy "HDNImages/nose1.png", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/nose1.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages"
    copy "HDNImages/pwm.png", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/pwm.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages"
    copy "HDNImages/rampdown.png", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/rampdown.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages"
    copy "HDNImages/rampup.png", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/rampup.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages"
    copy "HDNImages/silence.png", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/silence.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages"
    copy "HDNImages/sine.png", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/sine.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages"
    copy "HDNImages/sine_2.png", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/sine_2.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages"
    copy "HDNImages/sine_pi_b.png", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/sine_pi_b.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages"
    copy "HDNImages/sine_Wrp-b.png", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/sine_Wrp-b.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages"
    copy "HDNImages/sine_Wrp.png", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/sine_Wrp.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages"
    copy "HDNImages/sineSaw_level.png", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/sineSaw_level.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages"
    copy "HDNImages/sqr_Jpn.png", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/sqr_Jpn.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages"
    copy "HDNImages/square.png", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/square.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages"
    copy "HDNImages/Tri_alpha.png", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Tri_alpha.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages"
    copy "HDNImages/Tri_emb.png", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Tri_emb.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages"
    copy "HDNImages/triangle.png", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/triangle.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages"
    copy "HDNImages/using_patterns_0.png", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/using_patterns_0.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages"
    copy "HDNImages/w3.png", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/w3.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages"
    copy "HDNImages/w4_s_wte.png", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/w4_s_wte.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages"
    copy "HDNImages/w4_wte.png", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/w4_wte.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages"
    copy "HDNImages/wav.wav.png", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/wav.wav.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages"
    copy "HDNImages/wavy.png", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/wavy.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages"
    copy "HDNImages/wavy2.png", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/wavy2.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets"
    copy "HDNImages/Presets/awesome.fxp", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets/awesome.fxp"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets"
    copy "HDNImages/Presets/B.fxp", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets/B.fxp"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets"
    copy "HDNImages/Presets/blub.fxp", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets/blub.fxp"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets"
    copy "HDNImages/Presets/chug.fxp", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets/chug.fxp"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets"
    copy "HDNImages/Presets/cool.fxp", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets/cool.fxp"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets"
    copy "HDNImages/Presets/crucndgh.fxp", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets/crucndgh.fxp"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets"
    copy "HDNImages/Presets/crucndgh2.fxp", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets/crucndgh2.fxp"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets"
    copy "HDNImages/Presets/crucndgh3.fxp", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets/crucndgh3.fxp"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets"
    copy "HDNImages/Presets/flbn.fxb", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets/flbn.fxb"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets"
    copy "HDNImages/Presets/fun.fxp", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets/fun.fxp"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets"
    copy "HDNImages/Presets/ghnjhgf.fxp", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets/ghnjhgf.fxp"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets"
    copy "HDNImages/Presets/Harsh Digital Nose Default.fxp", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets/Harsh Digital Nose Default.fxp"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets"
    copy "HDNImages/Presets/Harsh Digital Nose Default2.fxp", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets/Harsh Digital Nose Default2.fxp"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets"
    copy "HDNImages/Presets/manilow.fxp", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets/manilow.fxp"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets"
    copy "HDNImages/Presets/Mtg_2_D3.fxp", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets/Mtg_2_D3.fxp"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets"
    copy "HDNImages/Presets/Mtg_D3.fxp", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets/Mtg_D3.fxp"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets"
    copy "HDNImages/Presets/nose.fxp", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets/nose.fxp"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets"
    copy "HDNImages/Presets/nose2.fxp", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets/nose2.fxp"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets"
    copy "HDNImages/Presets/o.fxp", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets/o.fxp"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets"
    copy "HDNImages/Presets/oh.fxp", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets/oh.fxp"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets"
    copy "HDNImages/Presets/ot.fxp", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets/ot.fxp"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets"
    copy "HDNImages/Presets/pwm.fxp", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets/pwm.fxp"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets"
    copy "HDNImages/Presets/qwqwqr.fxp", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets/qwqwqr.fxp"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets"
    copy "HDNImages/Presets/Sine_pi_D3.fxp", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets/Sine_pi_D3.fxp"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets"
    copy "HDNImages/Presets/uh.fxp", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets/uh.fxp"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets"
    copy "HDNImages/Presets/wwww.fxp", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets/wwww.fxp"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets"
    copy "HDNImages/Presets/yvsidbuof.fxp", "{{user}}/Library/Audio/Plug-Ins/VST/HDNImages/Presets/yvsidbuof.fxp"
  end
end
