cask "homecorrupter" do
  version "1.2.0"
  sha256 "3eeadf2e351fb6e8df4e276ac2d590a0da96cd176f612e4aa0bc1a0a51b4910b"
  url "https://github.com/igorski/homecorrupter/releases/download/1.2.0/homecorrupter.1.2.0_macos.zip"
  name "homecorrupter"
  desc "Free audio plugin"
  homepage "https://github.com/igorski/homecorrupter"
  depends_on :macos
  postflight_steps do
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3"
    move "AU/Homecorrupter AUV3.app/Contents/PlugIns/auv3.appex/Contents/PlugIns/plugin.vst3", "{{user}}/Library/Audio/Plug-Ins/VST3/plugin.vst3"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST"
    move "VST/homecorrupter.vst", "{{user}}/Library/Audio/Plug-Ins/VST/homecorrupter.vst"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3"
    move "VST3/homecorrupter.vst3", "{{user}}/Library/Audio/Plug-Ins/VST3/homecorrupter.vst3"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Homecorrupter AUV3.app/Contents"
    copy "AU/Homecorrupter AUV3.app/Contents/CodeResources", "{{user}}/Library/Audio/Plug-Ins/Components/Homecorrupter AUV3.app/Contents/CodeResources"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Homecorrupter AUV3.app/Contents"
    copy "AU/Homecorrupter AUV3.app/Contents/Info.plist", "{{user}}/Library/Audio/Plug-Ins/Components/Homecorrupter AUV3.app/Contents/Info.plist"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Homecorrupter AUV3.app/Contents"
    copy "AU/Homecorrupter AUV3.app/Contents/PkgInfo", "{{user}}/Library/Audio/Plug-Ins/Components/Homecorrupter AUV3.app/Contents/PkgInfo"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Homecorrupter AUV3.app/Contents/_CodeSignature"
    copy "AU/Homecorrupter AUV3.app/Contents/_CodeSignature/CodeResources", "{{user}}/Library/Audio/Plug-Ins/Components/Homecorrupter AUV3.app/Contents/_CodeSignature/CodeResources"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Homecorrupter AUV3.app/Contents/MacOS"
    copy "AU/Homecorrupter AUV3.app/Contents/MacOS/Homecorrupter AUV3", "{{user}}/Library/Audio/Plug-Ins/Components/Homecorrupter AUV3.app/Contents/MacOS/Homecorrupter AUV3"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Homecorrupter AUV3.app/Contents/Resources"
    copy "AU/Homecorrupter AUV3.app/Contents/Resources/loop.wav", "{{user}}/Library/Audio/Plug-Ins/Components/Homecorrupter AUV3.app/Contents/Resources/loop.wav"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Homecorrupter AUV3.app/Contents/Resources"
    copy "AU/Homecorrupter AUV3.app/Contents/Resources/plugin.icns", "{{user}}/Library/Audio/Plug-Ins/Components/Homecorrupter AUV3.app/Contents/Resources/plugin.icns"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Homecorrupter AUV3.app/Contents/Resources/Main.storyboardc"
    copy "AU/Homecorrupter AUV3.app/Contents/Resources/Main.storyboardc/MainMenu.nib", "{{user}}/Library/Audio/Plug-Ins/Components/Homecorrupter AUV3.app/Contents/Resources/Main.storyboardc/MainMenu.nib"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Homecorrupter AUV3.app/Contents/Resources/Main.storyboardc"
    copy "AU/Homecorrupter AUV3.app/Contents/Resources/Main.storyboardc/XfG-lQ-9wD-view-m2S-Jp-Qdl.nib", "{{user}}/Library/Audio/Plug-Ins/Components/Homecorrupter AUV3.app/Contents/Resources/Main.storyboardc/XfG-lQ-9wD-view-m2S-Jp-Qdl.nib"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Homecorrupter AUV3.app/Contents/Resources/Main.storyboardc"
    copy "AU/Homecorrupter AUV3.app/Contents/Resources/Main.storyboardc/NSWindowController-B8D-0N-5wS.nib", "{{user}}/Library/Audio/Plug-Ins/Components/Homecorrupter AUV3.app/Contents/Resources/Main.storyboardc/NSWindowController-B8D-0N-5wS.nib"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Homecorrupter AUV3.app/Contents/Resources/Main.storyboardc"
    copy "AU/Homecorrupter AUV3.app/Contents/Resources/Main.storyboardc/Info.plist", "{{user}}/Library/Audio/Plug-Ins/Components/Homecorrupter AUV3.app/Contents/Resources/Main.storyboardc/Info.plist"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Homecorrupter AUV3.app/Contents/PlugIns/auv3.appex/Contents"
    copy "AU/Homecorrupter AUV3.app/Contents/PlugIns/auv3.appex/Contents/Info.plist", "{{user}}/Library/Audio/Plug-Ins/Components/Homecorrupter AUV3.app/Contents/PlugIns/auv3.appex/Contents/Info.plist"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Homecorrupter AUV3.app/Contents/PlugIns/auv3.appex/Contents/_CodeSignature"
    copy "AU/Homecorrupter AUV3.app/Contents/PlugIns/auv3.appex/Contents/_CodeSignature/CodeResources", "{{user}}/Library/Audio/Plug-Ins/Components/Homecorrupter AUV3.app/Contents/PlugIns/auv3.appex/Contents/_CodeSignature/CodeResources"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Homecorrupter AUV3.app/Contents/PlugIns/auv3.appex/Contents/MacOS"
    copy "AU/Homecorrupter AUV3.app/Contents/PlugIns/auv3.appex/Contents/MacOS/homecorrupter_auv3_appextension_macos", "{{user}}/Library/Audio/Plug-Ins/Components/Homecorrupter AUV3.app/Contents/PlugIns/auv3.appex/Contents/MacOS/homecorrupter_auv3_appextension_macos"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Resources"
    copy "README.txt", "{{user}}/Library/Audio/Plug-Ins/Resources/README.txt"
  end
end
