cask "k3-v-extended-au" do
  version "latest"
  sha256 :no_check
  url "https://alt1.plugins4free.com/get_plug/K3-V_MacAU.zip"
  name "K3-V Extended"
  desc "K3-V Extended is an advanced emulation of the Kawai K3 wavetable synthesizer."
  homepage "https://plugins4free.com/plugin/2928"
  depends_on :macos
  postflight_steps do
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components"
    move "K3-V (Mac AU)/K3-V.component", "{{user}}/Library/Audio/Plug-Ins/Components/K3-V.component"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/K3-V Presets"
    copy "K3-V (Mac AU)/K3-V Presets/80's_Digital_Lead.aupreset", "{{user}}/Library/Audio/Plug-Ins/Components/K3-V Presets/80's_Digital_Lead.aupreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/K3-V Presets"
    copy "K3-V (Mac AU)/K3-V Presets/Digital_Synth.aupreset", "{{user}}/Library/Audio/Plug-Ins/Components/K3-V Presets/Digital_Synth.aupreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/K3-V Presets"
    copy "K3-V (Mac AU)/K3-V Presets/Grand_Piano_waveforms.aupreset", "{{user}}/Library/Audio/Plug-Ins/Components/K3-V Presets/Grand_Piano_waveforms.aupreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/K3-V Presets"
    copy "K3-V (Mac AU)/K3-V Presets/I_saw_a_synth.aupreset", "{{user}}/Library/Audio/Plug-Ins/Components/K3-V Presets/I_saw_a_synth.aupreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/K3-V Presets"
    copy "K3-V (Mac AU)/K3-V Presets/Matrix_12_Brass.aupreset", "{{user}}/Library/Audio/Plug-Ins/Components/K3-V Presets/Matrix_12_Brass.aupreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/K3-V Presets"
    copy "K3-V (Mac AU)/K3-V Presets/Patch__11.aupreset", "{{user}}/Library/Audio/Plug-Ins/Components/K3-V Presets/Patch__11.aupreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/K3-V Presets"
    copy "K3-V (Mac AU)/K3-V Presets/Patch__12.aupreset", "{{user}}/Library/Audio/Plug-Ins/Components/K3-V Presets/Patch__12.aupreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/K3-V Presets"
    copy "K3-V (Mac AU)/K3-V Presets/Patch__13.aupreset", "{{user}}/Library/Audio/Plug-Ins/Components/K3-V Presets/Patch__13.aupreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/K3-V Presets"
    copy "K3-V (Mac AU)/K3-V Presets/Patch__14.aupreset", "{{user}}/Library/Audio/Plug-Ins/Components/K3-V Presets/Patch__14.aupreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/K3-V Presets"
    copy "K3-V (Mac AU)/K3-V Presets/Patch__15.aupreset", "{{user}}/Library/Audio/Plug-Ins/Components/K3-V Presets/Patch__15.aupreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/K3-V Presets"
    copy "K3-V (Mac AU)/K3-V Presets/Patch__16.aupreset", "{{user}}/Library/Audio/Plug-Ins/Components/K3-V Presets/Patch__16.aupreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/K3-V Presets"
    copy "K3-V (Mac AU)/K3-V Presets/PPG.aupreset", "{{user}}/Library/Audio/Plug-Ins/Components/K3-V Presets/PPG.aupreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/K3-V Presets"
    copy "K3-V (Mac AU)/K3-V Presets/Soft_Pad.aupreset", "{{user}}/Library/Audio/Plug-Ins/Components/K3-V Presets/Soft_Pad.aupreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/K3-V Presets"
    copy "K3-V (Mac AU)/K3-V Presets/Supra_Chords.aupreset", "{{user}}/Library/Audio/Plug-Ins/Components/K3-V Presets/Supra_Chords.aupreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/K3-V Presets"
    copy "K3-V (Mac AU)/K3-V Presets/Sweet_Organ.aupreset", "{{user}}/Library/Audio/Plug-Ins/Components/K3-V Presets/Sweet_Organ.aupreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/K3-V Presets"
    copy "K3-V (Mac AU)/K3-V Presets/Wave_Bass.aupreset", "{{user}}/Library/Audio/Plug-Ins/Components/K3-V Presets/Wave_Bass.aupreset"
  end
end
