cask "micro-keys-vst" do
  version "latest"
  sha256 :no_check
  url "https://alt1.plugins4free.com/get_plug/Micro-Keys_MAC.zip"
  name "Micro Keys"
  desc "Micro Keys is a keyboard rompler ."
  homepage "https://plugins4free.com/plugin/3897"
  depends_on :macos
  postflight_steps do
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST"
    move "Micro Keys.vst", "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.vst"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.component/Contents/_CodeSignature"
    copy "Micro Keys.component/Contents/_CodeSignature/CodeResources", "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.component/Contents/_CodeSignature/CodeResources"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.component/Contents"
    copy "Micro Keys.component/Contents/CodeResources", "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.component/Contents/CodeResources"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.component/Contents"
    copy "Micro Keys.component/Contents/Info.plist", "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.component/Contents/Info.plist"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.component/Contents/MacOS"
    copy "Micro Keys.component/Contents/MacOS/MSP", "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.component/Contents/MacOS/MSP"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.component/Contents"
    copy "Micro Keys.component/Contents/PkgInfo", "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.component/Contents/PkgInfo"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.component/Contents/Resources"
    copy "Micro Keys.component/Contents/Resources/MSP.rsrc", "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.component/Contents/Resources/MSP.rsrc"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.component/Contents/Resources"
    copy "Micro Keys.component/Contents/Resources/RecentFilesMenuTemplate.nib", "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.component/Contents/Resources/RecentFilesMenuTemplate.nib"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments"
    copy "Micro Keys.instruments/01 CRYSTAL.mse", "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments/01 CRYSTAL.mse"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments"
    copy "Micro Keys.instruments/02 ELECTRO.mse", "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments/02 ELECTRO.mse"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments"
    copy "Micro Keys.instruments/03 ROADIES.mse", "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments/03 ROADIES.mse"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments"
    copy "Micro Keys.instruments/04 SUPREME.mse", "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments/04 SUPREME.mse"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments"
    copy "Micro Keys.instruments/05 JAZZDEN.mse", "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments/05 JAZZDEN.mse"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments"
    copy "Micro Keys.instruments/06 PIANSTR.mse", "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments/06 PIANSTR.mse"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments"
    copy "Micro Keys.instruments/07 FASTORG.mse", "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments/07 FASTORG.mse"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments"
    copy "Micro Keys.instruments/08 SLOWORG.mse", "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments/08 SLOWORG.mse"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments"
    copy "Micro Keys.instruments/09 FULLSTR.mse", "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments/09 FULLSTR.mse"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments"
    copy "Micro Keys.instruments/10 SMALSTR.mse", "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments/10 SMALSTR.mse"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments"
    copy "Micro Keys.instruments/11 SWELSTR.mse", "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments/11 SWELSTR.mse"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments"
    copy "Micro Keys.instruments/12 TRONSTR.mse", "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments/12 TRONSTR.mse"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments"
    copy "Micro Keys.instruments/13 PIZZSTR.mse", "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments/13 PIZZSTR.mse"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments"
    copy "Micro Keys.instruments/14 ATAKSTR.mse", "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments/14 ATAKSTR.mse"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments"
    copy "Micro Keys.instruments/15 MARCAT1.mse", "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments/15 MARCAT1.mse"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments"
    copy "Micro Keys.instruments/16 MARCAT2.mse", "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments/16 MARCAT2.mse"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments"
    copy "Micro Keys.instruments/17 BECKONS.mse", "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments/17 BECKONS.mse"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments"
    copy "Micro Keys.instruments/18 PHAT90S.mse", "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments/18 PHAT90S.mse"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments"
    copy "Micro Keys.instruments/19 EXPRESS.mse", "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments/19 EXPRESS.mse"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments"
    copy "Micro Keys.instruments/20 VECTORS.mse", "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments/20 VECTORS.mse"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments"
    copy "Micro Keys.instruments/21 FANTASY.mse", "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments/21 FANTASY.mse"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments"
    copy "Micro Keys.instruments/22 SYCHOIR.mse", "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments/22 SYCHOIR.mse"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments"
    copy "Micro Keys.instruments/23 HARMONY.mse", "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments/23 HARMONY.mse"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments"
    copy "Micro Keys.instruments/24 BOTTLED.mse", "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments/24 BOTTLED.mse"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments"
    copy "Micro Keys.instruments/25 TROPICS.mse", "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments/25 TROPICS.mse"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments"
    copy "Micro Keys.instruments/26 AMBIENT.mse", "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments/26 AMBIENT.mse"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments"
    copy "Micro Keys.instruments/27 DARKBAS.mse", "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments/27 DARKBAS.mse"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments"
    copy "Micro Keys.instruments/28 DEEPBAS.mse", "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments/28 DEEPBAS.mse"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments"
    copy "Micro Keys.instruments/29 HOUSE90.mse", "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments/29 HOUSE90.mse"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments"
    copy "Micro Keys.instruments/30 RESOBAS.mse", "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments/30 RESOBAS.mse"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments"
    copy "Micro Keys.instruments/31 CHAPSTK.mse", "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments/31 CHAPSTK.mse"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments"
    copy "Micro Keys.instruments/32 UPRIGHT.mse", "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments/32 UPRIGHT.mse"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments"
    copy "Micro Keys.instruments/33 TENOSAX.mse", "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.instruments/33 TENOSAX.mse"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.vst3/Contents/_CodeSignature"
    copy "Micro Keys.vst3/Contents/_CodeSignature/CodeResources", "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.vst3/Contents/_CodeSignature/CodeResources"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.vst3/Contents"
    copy "Micro Keys.vst3/Contents/CodeResources", "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.vst3/Contents/CodeResources"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.vst3/Contents"
    copy "Micro Keys.vst3/Contents/Info.plist", "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.vst3/Contents/Info.plist"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.vst3/Contents/MacOS"
    copy "Micro Keys.vst3/Contents/MacOS/MSP", "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.vst3/Contents/MacOS/MSP"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.vst3/Contents"
    copy "Micro Keys.vst3/Contents/PkgInfo", "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.vst3/Contents/PkgInfo"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.vst3/Contents/Resources"
    copy "Micro Keys.vst3/Contents/Resources/RecentFilesMenuTemplate.nib", "{{user}}/Library/Audio/Plug-Ins/VST/Micro Keys.vst3/Contents/Resources/RecentFilesMenuTemplate.nib"
  end
end
