cask "montagem-widener" do
  version "0.2.0-beta"
  sha256 "e5aa1d7d5d0c14c1356768987de5cb3b09ce98aacb281a6da184031aeb53aa37"
  url "https://github.com/nabsei/montagem-widener/releases/download/v0.2.0-beta/MontagemWidener_Beta_Mac.zip"
  name "montagem-widener"
  desc "Free audio plugin"
  homepage "https://github.com/nabsei/montagem-widener"
  depends_on :macos
  postflight_steps do
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components"
    move "Montagem Widener.component", "{{user}}/Library/Audio/Plug-Ins/Components/Montagem Widener.component"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components"
    copy "INSTALL.txt", "{{user}}/Library/Audio/Plug-Ins/Components/INSTALL.txt"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Montagem Widener.app/Contents/MacOS"
    copy "Montagem Widener.app/Contents/MacOS/Montagem Widener", "{{user}}/Library/Audio/Plug-Ins/Components/Montagem Widener.app/Contents/MacOS/Montagem Widener"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Montagem Widener.app/Contents/Resources"
    copy "Montagem Widener.app/Contents/Resources/RecentFilesMenuTemplate.nib", "{{user}}/Library/Audio/Plug-Ins/Components/Montagem Widener.app/Contents/Resources/RecentFilesMenuTemplate.nib"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Montagem Widener.app/Contents"
    copy "Montagem Widener.app/Contents/Info.plist", "{{user}}/Library/Audio/Plug-Ins/Components/Montagem Widener.app/Contents/Info.plist"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Montagem Widener.app/Contents"
    copy "Montagem Widener.app/Contents/PkgInfo", "{{user}}/Library/Audio/Plug-Ins/Components/Montagem Widener.app/Contents/PkgInfo"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components"
    copy "TERMS.txt", "{{user}}/Library/Audio/Plug-Ins/Components/TERMS.txt"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Montagem Widener.vst3/Contents/_CodeSignature"
    copy "Montagem Widener.vst3/Contents/_CodeSignature/CodeResources", "{{user}}/Library/Audio/Plug-Ins/Components/Montagem Widener.vst3/Contents/_CodeSignature/CodeResources"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Montagem Widener.vst3/Contents/MacOS"
    copy "Montagem Widener.vst3/Contents/MacOS/Montagem Widener", "{{user}}/Library/Audio/Plug-Ins/Components/Montagem Widener.vst3/Contents/MacOS/Montagem Widener"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Montagem Widener.vst3/Contents/Resources"
    copy "Montagem Widener.vst3/Contents/Resources/moduleinfo.json", "{{user}}/Library/Audio/Plug-Ins/Components/Montagem Widener.vst3/Contents/Resources/moduleinfo.json"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Montagem Widener.vst3/Contents"
    copy "Montagem Widener.vst3/Contents/Info.plist", "{{user}}/Library/Audio/Plug-Ins/Components/Montagem Widener.vst3/Contents/Info.plist"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Montagem Widener.vst3/Contents"
    copy "Montagem Widener.vst3/Contents/PkgInfo", "{{user}}/Library/Audio/Plug-Ins/Components/Montagem Widener.vst3/Contents/PkgInfo"
  end
end
