cask "montagem-808" do
  version "0.3.0-beta"
  sha256 "26eb62d8f527b820166ce0a04618f4f158fdfdee009e0ba2f101b7df677eceea"
  url "https://github.com/nabsei/montagem-808/releases/download/v0.3.0-beta/Montagem808_Beta_Mac.zip"
  name "montagem-808"
  desc "Free audio plugin"
  homepage "https://github.com/nabsei/montagem-808"
  depends_on :macos
  postflight_steps do
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components"
    move "Montagem 808.component", "{{user}}/Library/Audio/Plug-Ins/Components/Montagem 808.component"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components"
    copy "INSTALL.txt", "{{user}}/Library/Audio/Plug-Ins/Components/INSTALL.txt"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components"
    copy "TERMS.txt", "{{user}}/Library/Audio/Plug-Ins/Components/TERMS.txt"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Montagem 808.app/Contents/MacOS"
    copy "Montagem 808.app/Contents/MacOS/Montagem 808", "{{user}}/Library/Audio/Plug-Ins/Components/Montagem 808.app/Contents/MacOS/Montagem 808"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Montagem 808.app/Contents/Resources"
    copy "Montagem 808.app/Contents/Resources/RecentFilesMenuTemplate.nib", "{{user}}/Library/Audio/Plug-Ins/Components/Montagem 808.app/Contents/Resources/RecentFilesMenuTemplate.nib"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Montagem 808.app/Contents"
    copy "Montagem 808.app/Contents/Info.plist", "{{user}}/Library/Audio/Plug-Ins/Components/Montagem 808.app/Contents/Info.plist"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Montagem 808.app/Contents"
    copy "Montagem 808.app/Contents/PkgInfo", "{{user}}/Library/Audio/Plug-Ins/Components/Montagem 808.app/Contents/PkgInfo"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Montagem 808.vst3/Contents/_CodeSignature"
    copy "Montagem 808.vst3/Contents/_CodeSignature/CodeResources", "{{user}}/Library/Audio/Plug-Ins/Components/Montagem 808.vst3/Contents/_CodeSignature/CodeResources"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Montagem 808.vst3/Contents/MacOS"
    copy "Montagem 808.vst3/Contents/MacOS/Montagem 808", "{{user}}/Library/Audio/Plug-Ins/Components/Montagem 808.vst3/Contents/MacOS/Montagem 808"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Montagem 808.vst3/Contents/Resources"
    copy "Montagem 808.vst3/Contents/Resources/moduleinfo.json", "{{user}}/Library/Audio/Plug-Ins/Components/Montagem 808.vst3/Contents/Resources/moduleinfo.json"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Montagem 808.vst3/Contents"
    copy "Montagem 808.vst3/Contents/Info.plist", "{{user}}/Library/Audio/Plug-Ins/Components/Montagem 808.vst3/Contents/Info.plist"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Montagem 808.vst3/Contents"
    copy "Montagem 808.vst3/Contents/PkgInfo", "{{user}}/Library/Audio/Plug-Ins/Components/Montagem 808.vst3/Contents/PkgInfo"
  end
end
