cask "my-first-synth-vst" do
  version "latest"
  sha256 :no_check
  url "https://alt1.plugins4free.com/get_plug/MyFirstSynth_MacVST.zip"
  name "My First Synth"
  desc "My First Synth is a simple monophonic synthesizer ."
  homepage "https://plugins4free.com/plugin/2431"
  depends_on :macos
  postflight_steps do
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST"
    move "My First Synth.vst", "{{user}}/Library/Audio/Plug-Ins/VST/My First Synth.vst"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/My First Synth_x64.vst/Contents"
    copy "My First Synth_x64.vst/Contents/Info.plist", "{{user}}/Library/Audio/Plug-Ins/VST/My First Synth_x64.vst/Contents/Info.plist"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/My First Synth_x64.vst/Contents/MacOS"
    copy "My First Synth_x64.vst/Contents/MacOS/Synthesis", "{{user}}/Library/Audio/Plug-Ins/VST/My First Synth_x64.vst/Contents/MacOS/Synthesis"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/My First Synth_x64.vst/Contents"
    copy "My First Synth_x64.vst/Contents/PkgInfo", "{{user}}/Library/Audio/Plug-Ins/VST/My First Synth_x64.vst/Contents/PkgInfo"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/My First Synth_x64.vst/Contents/Resources"
    copy "My First Synth_x64.vst/Contents/Resources/about.png", "{{user}}/Library/Audio/Plug-Ins/VST/My First Synth_x64.vst/Contents/Resources/about.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/My First Synth_x64.vst/Contents/Resources"
    copy "My First Synth_x64.vst/Contents/Resources/bg.png", "{{user}}/Library/Audio/Plug-Ins/VST/My First Synth_x64.vst/Contents/Resources/bg.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/My First Synth_x64.vst/Contents/Resources"
    copy "My First Synth_x64.vst/Contents/Resources/blackkey.png", "{{user}}/Library/Audio/Plug-Ins/VST/My First Synth_x64.vst/Contents/Resources/blackkey.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/My First Synth_x64.vst/Contents/Resources"
    copy "My First Synth_x64.vst/Contents/Resources/filtermode.png", "{{user}}/Library/Audio/Plug-Ins/VST/My First Synth_x64.vst/Contents/Resources/filtermode.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/My First Synth_x64.vst/Contents/Resources"
    copy "My First Synth_x64.vst/Contents/Resources/knob.png", "{{user}}/Library/Audio/Plug-Ins/VST/My First Synth_x64.vst/Contents/Resources/knob.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/My First Synth_x64.vst/Contents/Resources"
    copy "My First Synth_x64.vst/Contents/Resources/knob_LFO.png", "{{user}}/Library/Audio/Plug-Ins/VST/My First Synth_x64.vst/Contents/Resources/knob_LFO.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/My First Synth_x64.vst/Contents/Resources"
    copy "My First Synth_x64.vst/Contents/Resources/knob_small.png", "{{user}}/Library/Audio/Plug-Ins/VST/My First Synth_x64.vst/Contents/Resources/knob_small.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/My First Synth_x64.vst/Contents/Resources"
    copy "My First Synth_x64.vst/Contents/Resources/stempel_transparent.png", "{{user}}/Library/Audio/Plug-Ins/VST/My First Synth_x64.vst/Contents/Resources/stempel_transparent.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/My First Synth_x64.vst/Contents/Resources"
    copy "My First Synth_x64.vst/Contents/Resources/Synthesis.rc", "{{user}}/Library/Audio/Plug-Ins/VST/My First Synth_x64.vst/Contents/Resources/Synthesis.rc"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/My First Synth_x64.vst/Contents/Resources"
    copy "My First Synth_x64.vst/Contents/Resources/vol_knob.png", "{{user}}/Library/Audio/Plug-Ins/VST/My First Synth_x64.vst/Contents/Resources/vol_knob.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/My First Synth_x64.vst/Contents/Resources"
    copy "My First Synth_x64.vst/Contents/Resources/waveform.png", "{{user}}/Library/Audio/Plug-Ins/VST/My First Synth_x64.vst/Contents/Resources/waveform.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/My First Synth_x64.vst/Contents/Resources"
    copy "My First Synth_x64.vst/Contents/Resources/waveform_LFO.png", "{{user}}/Library/Audio/Plug-Ins/VST/My First Synth_x64.vst/Contents/Resources/waveform_LFO.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/My First Synth_x64.vst/Contents/Resources"
    copy "My First Synth_x64.vst/Contents/Resources/whitekey.png", "{{user}}/Library/Audio/Plug-Ins/VST/My First Synth_x64.vst/Contents/Resources/whitekey.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST"
    copy "My First Synth README.txt", "{{user}}/Library/Audio/Plug-Ins/VST/My First Synth README.txt"
  end
end
