cask "nofish-dub-siren-au" do
  version "latest"
  sha256 :no_check
  url "https://alt1.plugins4free.com/get_plug/nofish-Dub-Siren_MacAU-1.01.zip"
  name "nofish Dub Siren"
  desc "nofish Dub Siren is a monophonic synth aiming to emulate these DIY devices used by Dub Sound Systems."
  homepage "https://plugins4free.com/plugin/2483"
  depends_on :macos
  postflight_steps do
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components"
    move "nofish Dub Siren Mac AU (1.0.1)/nofishs_Dub_Sirene.component", "{{user}}/Library/Audio/Plug-Ins/Components/nofishs_Dub_Sirene.component"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/nofishs_Dub_Sirene_x64.component/Contents"
    copy "nofish Dub Siren Mac AU (1.0.1)/nofishs_Dub_Sirene_x64.component/Contents/Info.plist", "{{user}}/Library/Audio/Plug-Ins/Components/nofishs_Dub_Sirene_x64.component/Contents/Info.plist"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/nofishs_Dub_Sirene_x64.component/Contents/MacOS"
    copy "nofish Dub Siren Mac AU (1.0.1)/nofishs_Dub_Sirene_x64.component/Contents/MacOS/nofishs_Dub_Sirene", "{{user}}/Library/Audio/Plug-Ins/Components/nofishs_Dub_Sirene_x64.component/Contents/MacOS/nofishs_Dub_Sirene"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/nofishs_Dub_Sirene_x64.component/Contents"
    copy "nofish Dub Siren Mac AU (1.0.1)/nofishs_Dub_Sirene_x64.component/Contents/PkgInfo", "{{user}}/Library/Audio/Plug-Ins/Components/nofishs_Dub_Sirene_x64.component/Contents/PkgInfo"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/nofishs_Dub_Sirene_x64.component/Contents/Resources"
    copy "nofish Dub Siren Mac AU (1.0.1)/nofishs_Dub_Sirene_x64.component/Contents/Resources/about_bckgnd.png", "{{user}}/Library/Audio/Plug-Ins/Components/nofishs_Dub_Sirene_x64.component/Contents/Resources/about_bckgnd.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/nofishs_Dub_Sirene_x64.component/Contents/Resources"
    copy "nofish Dub Siren Mac AU (1.0.1)/nofishs_Dub_Sirene_x64.component/Contents/Resources/background_Sunny.png", "{{user}}/Library/Audio/Plug-Ins/Components/nofishs_Dub_Sirene_x64.component/Contents/Resources/background_Sunny.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/nofishs_Dub_Sirene_x64.component/Contents/Resources"
    copy "nofish Dub Siren Mac AU (1.0.1)/nofishs_Dub_Sirene_x64.component/Contents/Resources/blank_46_46_logo.png", "{{user}}/Library/Audio/Plug-Ins/Components/nofishs_Dub_Sirene_x64.component/Contents/Resources/blank_46_46_logo.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/nofishs_Dub_Sirene_x64.component/Contents/Resources"
    copy "nofish Dub Siren Mac AU (1.0.1)/nofishs_Dub_Sirene_x64.component/Contents/Resources/dub knob big 121.png", "{{user}}/Library/Audio/Plug-Ins/Components/nofishs_Dub_Sirene_x64.component/Contents/Resources/dub knob big 121.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/nofishs_Dub_Sirene_x64.component/Contents/Resources"
    copy "nofish Dub Siren Mac AU (1.0.1)/nofishs_Dub_Sirene_x64.component/Contents/Resources/dub knob small 121.png", "{{user}}/Library/Audio/Plug-Ins/Components/nofishs_Dub_Sirene_x64.component/Contents/Resources/dub knob small 121.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/nofishs_Dub_Sirene_x64.component/Contents/Resources"
    copy "nofish Dub Siren Mac AU (1.0.1)/nofishs_Dub_Sirene_x64.component/Contents/Resources/dub knob small transparent.png", "{{user}}/Library/Audio/Plug-Ins/Components/nofishs_Dub_Sirene_x64.component/Contents/Resources/dub knob small transparent.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/nofishs_Dub_Sirene_x64.component/Contents/Resources"
    copy "nofish Dub Siren Mac AU (1.0.1)/nofishs_Dub_Sirene_x64.component/Contents/Resources/dub knob small v2 transparent.png", "{{user}}/Library/Audio/Plug-Ins/Components/nofishs_Dub_Sirene_x64.component/Contents/Resources/dub knob small v2 transparent.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/nofishs_Dub_Sirene_x64.component/Contents/Resources"
    copy "nofish Dub Siren Mac AU (1.0.1)/nofishs_Dub_Sirene_x64.component/Contents/Resources/dub led small.png", "{{user}}/Library/Audio/Plug-Ins/Components/nofishs_Dub_Sirene_x64.component/Contents/Resources/dub led small.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/nofishs_Dub_Sirene_x64.component/Contents/Resources"
    copy "nofish Dub Siren Mac AU (1.0.1)/nofishs_Dub_Sirene_x64.component/Contents/Resources/dub switch big d.png", "{{user}}/Library/Audio/Plug-Ins/Components/nofishs_Dub_Sirene_x64.component/Contents/Resources/dub switch big d.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/nofishs_Dub_Sirene_x64.component/Contents/Resources"
    copy "nofish Dub Siren Mac AU (1.0.1)/nofishs_Dub_Sirene_x64.component/Contents/Resources/dub switch d.png", "{{user}}/Library/Audio/Plug-Ins/Components/nofishs_Dub_Sirene_x64.component/Contents/Resources/dub switch d.png"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/nofishs_Dub_Sirene_x64.component/Contents/Resources"
    copy "nofish Dub Siren Mac AU (1.0.1)/nofishs_Dub_Sirene_x64.component/Contents/Resources/nofishs_Dub_Sirene.rsrc", "{{user}}/Library/Audio/Plug-Ins/Components/nofishs_Dub_Sirene_x64.component/Contents/Resources/nofishs_Dub_Sirene.rsrc"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/nofishs_Dub_Sirene_x64.component/Contents/Resources"
    copy "nofish Dub Siren Mac AU (1.0.1)/nofishs_Dub_Sirene_x64.component/Contents/Resources/waveforms.png", "{{user}}/Library/Audio/Plug-Ins/Components/nofishs_Dub_Sirene_x64.component/Contents/Resources/waveforms.png"
  end
end
