cask "peakeater" do
  version "0.8.2"
  sha256 "0df88ee26481843d0cc7762377bfefbb489a147a96fe6a9f2b9962834b92ba06"
  url "https://github.com/vvvar/PeakEater/releases/download/v0.8.2/peakeater-v0.8.2-macOS-universal.dmg"
  name "PeakEater"
  desc "Free wave-shaping audio plugin"
  homepage "https://github.com/vvvar/PeakEater"
  depends_on :macos
  container type: :dmg
  postflight_steps do
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/CLAP"
    move "peakeater.clap", "{{user}}/Library/Audio/Plug-Ins/CLAP/peakeater.clap"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/CLAP"
    copy "CLAP", "{{user}}/Library/Audio/Plug-Ins/CLAP/CLAP"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/CLAP"
    copy "LV2", "{{user}}/Library/Audio/Plug-Ins/CLAP/LV2"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/CLAP"
    copy "VST3", "{{user}}/Library/Audio/Plug-Ins/CLAP/VST3"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/CLAP/peakeater.component/Contents"
    copy "peakeater.component/Contents/Info.plist", "{{user}}/Library/Audio/Plug-Ins/CLAP/peakeater.component/Contents/Info.plist"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/CLAP/peakeater.component/Contents"
    copy "peakeater.component/Contents/PkgInfo", "{{user}}/Library/Audio/Plug-Ins/CLAP/peakeater.component/Contents/PkgInfo"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/CLAP/peakeater.component/Contents/_CodeSignature"
    copy "peakeater.component/Contents/_CodeSignature/CodeResources", "{{user}}/Library/Audio/Plug-Ins/CLAP/peakeater.component/Contents/_CodeSignature/CodeResources"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/CLAP/peakeater.component/Contents/MacOS"
    copy "peakeater.component/Contents/MacOS/peakeater", "{{user}}/Library/Audio/Plug-Ins/CLAP/peakeater.component/Contents/MacOS/peakeater"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/CLAP/peakeater.lv2"
    copy "peakeater.lv2/dsp.ttl", "{{user}}/Library/Audio/Plug-Ins/CLAP/peakeater.lv2/dsp.ttl"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/CLAP/peakeater.lv2"
    copy "peakeater.lv2/libpeakeater.so", "{{user}}/Library/Audio/Plug-Ins/CLAP/peakeater.lv2/libpeakeater.so"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/CLAP/peakeater.lv2"
    copy "peakeater.lv2/manifest.ttl", "{{user}}/Library/Audio/Plug-Ins/CLAP/peakeater.lv2/manifest.ttl"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/CLAP/peakeater.lv2"
    copy "peakeater.lv2/ui.ttl", "{{user}}/Library/Audio/Plug-Ins/CLAP/peakeater.lv2/ui.ttl"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/CLAP/peakeater.vst3/Contents"
    copy "peakeater.vst3/Contents/Info.plist", "{{user}}/Library/Audio/Plug-Ins/CLAP/peakeater.vst3/Contents/Info.plist"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/CLAP/peakeater.vst3/Contents"
    copy "peakeater.vst3/Contents/PkgInfo", "{{user}}/Library/Audio/Plug-Ins/CLAP/peakeater.vst3/Contents/PkgInfo"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/CLAP/peakeater.vst3/Contents/_CodeSignature"
    copy "peakeater.vst3/Contents/_CodeSignature/CodeResources", "{{user}}/Library/Audio/Plug-Ins/CLAP/peakeater.vst3/Contents/_CodeSignature/CodeResources"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/CLAP/peakeater.vst3/Contents/MacOS"
    copy "peakeater.vst3/Contents/MacOS/peakeater", "{{user}}/Library/Audio/Plug-Ins/CLAP/peakeater.vst3/Contents/MacOS/peakeater"
  end
end
