cask "promptslice" do
  version "0.1.0"
  sha256 "036dc78ab1184b91615e6df2e4efde16706df1f4ca877042d01c9cbe63730fb7"
  url "https://github.com/vasylNaumenko/promptslice/releases/download/v0.1.0/PromptSlice-v0.1.0-macOS.zip"
  name "promptslice"
  desc "Free audio plugin"
  homepage "https://github.com/vasylNaumenko/promptslice"
  depends_on :macos
  postflight_steps do
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components"
    move "PromptSlice/PromptSlice.component", "{{user}}/Library/Audio/Plug-Ins/Components/PromptSlice.component"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/PromptSlice.vst3/Contents/_CodeSignature"
    copy "PromptSlice/PromptSlice.vst3/Contents/_CodeSignature/CodeResources", "{{user}}/Library/Audio/Plug-Ins/Components/PromptSlice.vst3/Contents/_CodeSignature/CodeResources"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/PromptSlice.vst3/Contents/MacOS"
    copy "PromptSlice/PromptSlice.vst3/Contents/MacOS/PromptSlice", "{{user}}/Library/Audio/Plug-Ins/Components/PromptSlice.vst3/Contents/MacOS/PromptSlice"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/PromptSlice.vst3/Contents/Resources"
    copy "PromptSlice/PromptSlice.vst3/Contents/Resources/moduleinfo.json", "{{user}}/Library/Audio/Plug-Ins/Components/PromptSlice.vst3/Contents/Resources/moduleinfo.json"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/PromptSlice.vst3/Contents"
    copy "PromptSlice/PromptSlice.vst3/Contents/Info.plist", "{{user}}/Library/Audio/Plug-Ins/Components/PromptSlice.vst3/Contents/Info.plist"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/PromptSlice.vst3/Contents"
    copy "PromptSlice/PromptSlice.vst3/Contents/PkgInfo", "{{user}}/Library/Audio/Plug-Ins/Components/PromptSlice.vst3/Contents/PkgInfo"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/PromptSlice.app/Contents/MacOS"
    copy "PromptSlice/PromptSlice.app/Contents/MacOS/PromptSlice", "{{user}}/Library/Audio/Plug-Ins/Components/PromptSlice.app/Contents/MacOS/PromptSlice"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/PromptSlice.app/Contents/Resources"
    copy "PromptSlice/PromptSlice.app/Contents/Resources/RecentFilesMenuTemplate.nib", "{{user}}/Library/Audio/Plug-Ins/Components/PromptSlice.app/Contents/Resources/RecentFilesMenuTemplate.nib"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/PromptSlice.app/Contents"
    copy "PromptSlice/PromptSlice.app/Contents/Info.plist", "{{user}}/Library/Audio/Plug-Ins/Components/PromptSlice.app/Contents/Info.plist"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/PromptSlice.app/Contents"
    copy "PromptSlice/PromptSlice.app/Contents/PkgInfo", "{{user}}/Library/Audio/Plug-Ins/Components/PromptSlice.app/Contents/PkgInfo"
  end
end
