cask "re-deemer" do
  version "1.1.4"
  sha256 "5ed34a537dbb9f0d4497747bfeffa8235aa14c8cd11ff7add71f13e499511240"
  url "https://github.com/naturarum/re-deemer/releases/download/v1.1.4/RE-DEEMER-1.1.4-macos.zip"
  name "re-deemer"
  desc "Free audio plugin"
  homepage "https://github.com/naturarum/re-deemer"
  depends_on :macos
  postflight_steps do
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components"
    move "RE-DEEMER/RE-DEEMER.component", "{{user}}/Library/Audio/Plug-Ins/Components/RE-DEEMER.component"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components"
    copy "RE-DEEMER/LICENSE", "{{user}}/Library/Audio/Plug-Ins/Components/LICENSE"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components"
    copy "RE-DEEMER/install.sh", "{{user}}/Library/Audio/Plug-Ins/Components/install.sh"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/RE-DEEMER.vst3/Contents"
    copy "RE-DEEMER/RE-DEEMER.vst3/Contents/CodeResources", "{{user}}/Library/Audio/Plug-Ins/Components/RE-DEEMER.vst3/Contents/CodeResources"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/RE-DEEMER.vst3/Contents/_CodeSignature"
    copy "RE-DEEMER/RE-DEEMER.vst3/Contents/_CodeSignature/CodeResources", "{{user}}/Library/Audio/Plug-Ins/Components/RE-DEEMER.vst3/Contents/_CodeSignature/CodeResources"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/RE-DEEMER.vst3/Contents/MacOS"
    copy "RE-DEEMER/RE-DEEMER.vst3/Contents/MacOS/RE-DEEMER", "{{user}}/Library/Audio/Plug-Ins/Components/RE-DEEMER.vst3/Contents/MacOS/RE-DEEMER"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/RE-DEEMER.vst3/Contents"
    copy "RE-DEEMER/RE-DEEMER.vst3/Contents/Info.plist", "{{user}}/Library/Audio/Plug-Ins/Components/RE-DEEMER.vst3/Contents/Info.plist"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/RE-DEEMER.vst3/Contents"
    copy "RE-DEEMER/RE-DEEMER.vst3/Contents/PkgInfo", "{{user}}/Library/Audio/Plug-Ins/Components/RE-DEEMER.vst3/Contents/PkgInfo"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components"
    copy "RE-DEEMER/VERSION.txt", "{{user}}/Library/Audio/Plug-Ins/Components/VERSION.txt"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components"
    copy "RE-DEEMER/MANUAL.md", "{{user}}/Library/Audio/Plug-Ins/Components/MANUAL.md"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/RE-DEEMER.clap/Contents"
    copy "RE-DEEMER/RE-DEEMER.clap/Contents/CodeResources", "{{user}}/Library/Audio/Plug-Ins/Components/RE-DEEMER.clap/Contents/CodeResources"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/RE-DEEMER.clap/Contents/_CodeSignature"
    copy "RE-DEEMER/RE-DEEMER.clap/Contents/_CodeSignature/CodeResources", "{{user}}/Library/Audio/Plug-Ins/Components/RE-DEEMER.clap/Contents/_CodeSignature/CodeResources"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/RE-DEEMER.clap/Contents/MacOS"
    copy "RE-DEEMER/RE-DEEMER.clap/Contents/MacOS/RE-DEEMER", "{{user}}/Library/Audio/Plug-Ins/Components/RE-DEEMER.clap/Contents/MacOS/RE-DEEMER"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/RE-DEEMER.clap/Contents"
    copy "RE-DEEMER/RE-DEEMER.clap/Contents/Info.plist", "{{user}}/Library/Audio/Plug-Ins/Components/RE-DEEMER.clap/Contents/Info.plist"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/RE-DEEMER.clap/Contents"
    copy "RE-DEEMER/RE-DEEMER.clap/Contents/PkgInfo", "{{user}}/Library/Audio/Plug-Ins/Components/RE-DEEMER.clap/Contents/PkgInfo"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components"
    copy "RE-DEEMER/PRESETS.md", "{{user}}/Library/Audio/Plug-Ins/Components/PRESETS.md"
  end
end
