cask "rechoir" do
  version "1.0.0"
  sha256 "7a1df5f354177c9abd9f2871a306e6b961df310c901dc199d535d5924ad2ff13"
  url "https://github.com/igorski/rechoir/releases/download/1.0.0/rechoir.1.0.0_macos.zip"
  name "rechoir"
  desc "Free audio plugin"
  homepage "https://github.com/igorski/rechoir"
  depends_on :macos
  postflight_steps do
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3"
    move "AU/Rechoir AUV3.app/Contents/PlugIns/auv3.appex/Contents/PlugIns/plugin.vst3", "{{user}}/Library/Audio/Plug-Ins/VST3/plugin.vst3"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST"
    move "VST/Rechoir.vst", "{{user}}/Library/Audio/Plug-Ins/VST/Rechoir.vst"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3"
    move "VST3/Rechoir.vst3", "{{user}}/Library/Audio/Plug-Ins/VST3/Rechoir.vst3"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Rechoir AUV3.app/Contents"
    copy "AU/Rechoir AUV3.app/Contents/CodeResources", "{{user}}/Library/Audio/Plug-Ins/Components/Rechoir AUV3.app/Contents/CodeResources"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Rechoir AUV3.app/Contents"
    copy "AU/Rechoir AUV3.app/Contents/Info.plist", "{{user}}/Library/Audio/Plug-Ins/Components/Rechoir AUV3.app/Contents/Info.plist"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Rechoir AUV3.app/Contents"
    copy "AU/Rechoir AUV3.app/Contents/PkgInfo", "{{user}}/Library/Audio/Plug-Ins/Components/Rechoir AUV3.app/Contents/PkgInfo"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Rechoir AUV3.app/Contents/_CodeSignature"
    copy "AU/Rechoir AUV3.app/Contents/_CodeSignature/CodeResources", "{{user}}/Library/Audio/Plug-Ins/Components/Rechoir AUV3.app/Contents/_CodeSignature/CodeResources"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Rechoir AUV3.app/Contents/MacOS"
    copy "AU/Rechoir AUV3.app/Contents/MacOS/Rechoir AUV3", "{{user}}/Library/Audio/Plug-Ins/Components/Rechoir AUV3.app/Contents/MacOS/Rechoir AUV3"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Rechoir AUV3.app/Contents/Resources"
    copy "AU/Rechoir AUV3.app/Contents/Resources/loop.wav", "{{user}}/Library/Audio/Plug-Ins/Components/Rechoir AUV3.app/Contents/Resources/loop.wav"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Rechoir AUV3.app/Contents/Resources"
    copy "AU/Rechoir AUV3.app/Contents/Resources/plugin.icns", "{{user}}/Library/Audio/Plug-Ins/Components/Rechoir AUV3.app/Contents/Resources/plugin.icns"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Rechoir AUV3.app/Contents/Resources/Main.storyboardc"
    copy "AU/Rechoir AUV3.app/Contents/Resources/Main.storyboardc/MainMenu.nib", "{{user}}/Library/Audio/Plug-Ins/Components/Rechoir AUV3.app/Contents/Resources/Main.storyboardc/MainMenu.nib"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Rechoir AUV3.app/Contents/Resources/Main.storyboardc"
    copy "AU/Rechoir AUV3.app/Contents/Resources/Main.storyboardc/XfG-lQ-9wD-view-m2S-Jp-Qdl.nib", "{{user}}/Library/Audio/Plug-Ins/Components/Rechoir AUV3.app/Contents/Resources/Main.storyboardc/XfG-lQ-9wD-view-m2S-Jp-Qdl.nib"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Rechoir AUV3.app/Contents/Resources/Main.storyboardc"
    copy "AU/Rechoir AUV3.app/Contents/Resources/Main.storyboardc/NSWindowController-B8D-0N-5wS.nib", "{{user}}/Library/Audio/Plug-Ins/Components/Rechoir AUV3.app/Contents/Resources/Main.storyboardc/NSWindowController-B8D-0N-5wS.nib"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Rechoir AUV3.app/Contents/Resources/Main.storyboardc"
    copy "AU/Rechoir AUV3.app/Contents/Resources/Main.storyboardc/Info.plist", "{{user}}/Library/Audio/Plug-Ins/Components/Rechoir AUV3.app/Contents/Resources/Main.storyboardc/Info.plist"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Rechoir AUV3.app/Contents/PlugIns/auv3.appex/Contents"
    copy "AU/Rechoir AUV3.app/Contents/PlugIns/auv3.appex/Contents/Info.plist", "{{user}}/Library/Audio/Plug-Ins/Components/Rechoir AUV3.app/Contents/PlugIns/auv3.appex/Contents/Info.plist"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Rechoir AUV3.app/Contents/PlugIns/auv3.appex/Contents/_CodeSignature"
    copy "AU/Rechoir AUV3.app/Contents/PlugIns/auv3.appex/Contents/_CodeSignature/CodeResources", "{{user}}/Library/Audio/Plug-Ins/Components/Rechoir AUV3.app/Contents/PlugIns/auv3.appex/Contents/_CodeSignature/CodeResources"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Rechoir AUV3.app/Contents/PlugIns/auv3.appex/Contents/MacOS"
    copy "AU/Rechoir AUV3.app/Contents/PlugIns/auv3.appex/Contents/MacOS/rechoir_auv3_appextension_macos", "{{user}}/Library/Audio/Plug-Ins/Components/Rechoir AUV3.app/Contents/PlugIns/auv3.appex/Contents/MacOS/rechoir_auv3_appextension_macos"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Resources"
    copy "README.txt", "{{user}}/Library/Audio/Plug-Ins/Resources/README.txt"
  end
end
