cask "regrader" do
  version "1.0.5"
  sha256 "d3b77b466f270888fb866e67c86fafcdfafc9ff781420ca9ab77da7c7987f356"
  url "https://github.com/igorski/regrader/releases/download/1.0.5/regrader.1.0.5_macos.zip"
  name "regrader"
  desc "Free audio plugin"
  homepage "https://github.com/igorski/regrader"
  depends_on :macos
  postflight_steps do
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST"
    move "VST/regrader.vst", "{{user}}/Library/Audio/Plug-Ins/VST/regrader.vst"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3"
    move "VST3/regrader.vst3", "{{user}}/Library/Audio/Plug-Ins/VST3/regrader.vst3"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3"
    move "AU/Regrader AUV3.app/Contents/PlugIns/auv3.appex/Contents/PlugIns/plugin.vst3", "{{user}}/Library/Audio/Plug-Ins/VST3/plugin.vst3"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Regrader AUV3.app/Contents"
    copy "AU/Regrader AUV3.app/Contents/CodeResources", "{{user}}/Library/Audio/Plug-Ins/Components/Regrader AUV3.app/Contents/CodeResources"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Regrader AUV3.app/Contents"
    copy "AU/Regrader AUV3.app/Contents/Info.plist", "{{user}}/Library/Audio/Plug-Ins/Components/Regrader AUV3.app/Contents/Info.plist"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Regrader AUV3.app/Contents"
    copy "AU/Regrader AUV3.app/Contents/PkgInfo", "{{user}}/Library/Audio/Plug-Ins/Components/Regrader AUV3.app/Contents/PkgInfo"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Regrader AUV3.app/Contents/_CodeSignature"
    copy "AU/Regrader AUV3.app/Contents/_CodeSignature/CodeResources", "{{user}}/Library/Audio/Plug-Ins/Components/Regrader AUV3.app/Contents/_CodeSignature/CodeResources"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Regrader AUV3.app/Contents/MacOS"
    copy "AU/Regrader AUV3.app/Contents/MacOS/Regrader AUV3", "{{user}}/Library/Audio/Plug-Ins/Components/Regrader AUV3.app/Contents/MacOS/Regrader AUV3"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Regrader AUV3.app/Contents/Resources"
    copy "AU/Regrader AUV3.app/Contents/Resources/loop.wav", "{{user}}/Library/Audio/Plug-Ins/Components/Regrader AUV3.app/Contents/Resources/loop.wav"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Regrader AUV3.app/Contents/Resources"
    copy "AU/Regrader AUV3.app/Contents/Resources/plugin.icns", "{{user}}/Library/Audio/Plug-Ins/Components/Regrader AUV3.app/Contents/Resources/plugin.icns"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Regrader AUV3.app/Contents/Resources/Main.storyboardc"
    copy "AU/Regrader AUV3.app/Contents/Resources/Main.storyboardc/MainMenu.nib", "{{user}}/Library/Audio/Plug-Ins/Components/Regrader AUV3.app/Contents/Resources/Main.storyboardc/MainMenu.nib"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Regrader AUV3.app/Contents/Resources/Main.storyboardc"
    copy "AU/Regrader AUV3.app/Contents/Resources/Main.storyboardc/XfG-lQ-9wD-view-m2S-Jp-Qdl.nib", "{{user}}/Library/Audio/Plug-Ins/Components/Regrader AUV3.app/Contents/Resources/Main.storyboardc/XfG-lQ-9wD-view-m2S-Jp-Qdl.nib"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Regrader AUV3.app/Contents/Resources/Main.storyboardc"
    copy "AU/Regrader AUV3.app/Contents/Resources/Main.storyboardc/NSWindowController-B8D-0N-5wS.nib", "{{user}}/Library/Audio/Plug-Ins/Components/Regrader AUV3.app/Contents/Resources/Main.storyboardc/NSWindowController-B8D-0N-5wS.nib"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Regrader AUV3.app/Contents/Resources/Main.storyboardc"
    copy "AU/Regrader AUV3.app/Contents/Resources/Main.storyboardc/Info.plist", "{{user}}/Library/Audio/Plug-Ins/Components/Regrader AUV3.app/Contents/Resources/Main.storyboardc/Info.plist"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Regrader AUV3.app/Contents/PlugIns/auv3.appex/Contents"
    copy "AU/Regrader AUV3.app/Contents/PlugIns/auv3.appex/Contents/Info.plist", "{{user}}/Library/Audio/Plug-Ins/Components/Regrader AUV3.app/Contents/PlugIns/auv3.appex/Contents/Info.plist"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Regrader AUV3.app/Contents/PlugIns/auv3.appex/Contents/_CodeSignature"
    copy "AU/Regrader AUV3.app/Contents/PlugIns/auv3.appex/Contents/_CodeSignature/CodeResources", "{{user}}/Library/Audio/Plug-Ins/Components/Regrader AUV3.app/Contents/PlugIns/auv3.appex/Contents/_CodeSignature/CodeResources"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Regrader AUV3.app/Contents/PlugIns/auv3.appex/Contents/MacOS"
    copy "AU/Regrader AUV3.app/Contents/PlugIns/auv3.appex/Contents/MacOS/regrader_auv3_appextension_macos", "{{user}}/Library/Audio/Plug-Ins/Components/Regrader AUV3.app/Contents/PlugIns/auv3.appex/Contents/MacOS/regrader_auv3_appextension_macos"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Resources"
    copy "README.txt", "{{user}}/Library/Audio/Plug-Ins/Resources/README.txt"
  end
end
