cask "spiral-generator-vst" do
  version "latest"
  sha256 :no_check
  url "https://alt1.plugins4free.com/get_plug/SpiralGenerator_MacVST.zip"
  name "Spiral Generator"
  desc "Spiral Generator is an oscilloscope-music inspired 3D synthesizer ."
  homepage "https://plugins4free.com/plugin/2778"
  depends_on :macos
  postflight_steps do
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST"
    move "SpiralGenerator.vst", "{{user}}/Library/Audio/Plug-Ins/VST/SpiralGenerator.vst"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Presets"
    copy "Presets/Bass_DubSteppy.xml", "{{user}}/Library/Audio/Plug-Ins/VST/Presets/Bass_DubSteppy.xml"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Presets"
    copy "Presets/Bass_ReallyVocal.xml", "{{user}}/Library/Audio/Plug-Ins/VST/Presets/Bass_ReallyVocal.xml"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Presets"
    copy "Presets/Bass_Throaty.xml", "{{user}}/Library/Audio/Plug-Ins/VST/Presets/Bass_Throaty.xml"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Presets"
    copy "Presets/FX_CrunchySpirals.xml", "{{user}}/Library/Audio/Plug-Ins/VST/Presets/FX_CrunchySpirals.xml"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Presets"
    copy "Presets/FX_CrunchySpirals2.xml", "{{user}}/Library/Audio/Plug-Ins/VST/Presets/FX_CrunchySpirals2.xml"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Presets"
    copy "Presets/FX_EyeOfTheSpiral.xml", "{{user}}/Library/Audio/Plug-Ins/VST/Presets/FX_EyeOfTheSpiral.xml"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Presets"
    copy "Presets/FX_GasPoweredSpirals.xml", "{{user}}/Library/Audio/Plug-Ins/VST/Presets/FX_GasPoweredSpirals.xml"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Presets"
    copy "Presets/FX_HarmonicLocking.xml", "{{user}}/Library/Audio/Plug-Ins/VST/Presets/FX_HarmonicLocking.xml"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Presets"
    copy "Presets/FX_HarmonicLocking2.xml", "{{user}}/Library/Audio/Plug-Ins/VST/Presets/FX_HarmonicLocking2.xml"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Presets"
    copy "Presets/FX_RisingEngineSounds.xml", "{{user}}/Library/Audio/Plug-Ins/VST/Presets/FX_RisingEngineSounds.xml"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Presets"
    copy "Presets/FX_RotatingAndHowling.xml", "{{user}}/Library/Audio/Plug-Ins/VST/Presets/FX_RotatingAndHowling.xml"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Presets"
    copy "Presets/FX_SpiralTornado.xml", "{{user}}/Library/Audio/Plug-Ins/VST/Presets/FX_SpiralTornado.xml"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Presets"
    copy "Presets/FX_StopDrippingOnMe.xml", "{{user}}/Library/Audio/Plug-Ins/VST/Presets/FX_StopDrippingOnMe.xml"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Presets"
    copy "Presets/FX_StopLaughingAtME.xml", "{{user}}/Library/Audio/Plug-Ins/VST/Presets/FX_StopLaughingAtME.xml"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Presets"
    copy "Presets/FX_StopSpinningYouCrazy.xml", "{{user}}/Library/Audio/Plug-Ins/VST/Presets/FX_StopSpinningYouCrazy.xml"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Presets"
    copy "Presets/FX_StopSpinningYouCrazy2.xml", "{{user}}/Library/Audio/Plug-Ins/VST/Presets/FX_StopSpinningYouCrazy2.xml"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Presets"
    copy "Presets/FX_TheyreComing.xml", "{{user}}/Library/Audio/Plug-Ins/VST/Presets/FX_TheyreComing.xml"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Presets"
    copy "Presets/FX_ThisAintYourGrandmothersThumps.xml", "{{user}}/Library/Audio/Plug-Ins/VST/Presets/FX_ThisAintYourGrandmothersThumps.xml"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Presets"
    copy "Presets/Lead_Heartistic.xml", "{{user}}/Library/Audio/Plug-Ins/VST/Presets/Lead_Heartistic.xml"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Presets"
    copy "Presets/Lead_HeartyArp.xml", "{{user}}/Library/Audio/Plug-Ins/VST/Presets/Lead_HeartyArp.xml"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Presets"
    copy "Presets/Lead_HeartyArp2(Square).xml", "{{user}}/Library/Audio/Plug-Ins/VST/Presets/Lead_HeartyArp2(Square).xml"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Presets"
    copy "Presets/Lead_WildSpiral.xml", "{{user}}/Library/Audio/Plug-Ins/VST/Presets/Lead_WildSpiral.xml"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Presets"
    copy "Presets/PATTERN_2DFractal.xml", "{{user}}/Library/Audio/Plug-Ins/VST/Presets/PATTERN_2DFractal.xml"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Presets"
    copy "Presets/PATTERN_Amazing.xml", "{{user}}/Library/Audio/Plug-Ins/VST/Presets/PATTERN_Amazing.xml"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Presets"
    copy "Presets/PATTERN_DifferentKeysDifferentFolks.xml", "{{user}}/Library/Audio/Plug-Ins/VST/Presets/PATTERN_DifferentKeysDifferentFolks.xml"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Presets"
    copy "Presets/PATTERN_GoldenSpi.xml", "{{user}}/Library/Audio/Plug-Ins/VST/Presets/PATTERN_GoldenSpi.xml"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Presets"
    copy "Presets/PATTERN_OohFuzzy.xml", "{{user}}/Library/Audio/Plug-Ins/VST/Presets/PATTERN_OohFuzzy.xml"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/Presets"
    copy "Presets/PATTERN_Starry.xml", "{{user}}/Library/Audio/Plug-Ins/VST/Presets/PATTERN_Starry.xml"
  end
end
