cask "syncla-x-au" do
  version "latest"
  sha256 :no_check
  url "https://alt1.plugins4free.com/get_plug/Syncla-X_MacAU.zip"
  name "Syncla-X"
  desc "Syncla-X is a Synclavier II FM synthesizer emulation."
  homepage "https://plugins4free.com/plugin/2929"
  depends_on :macos
  postflight_steps do
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components"
    move "Syncla-X [Mac AU]/Syncla-X.component", "{{user}}/Library/Audio/Plug-Ins/Components/Syncla-X.component"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Syncla-X Presets"
    copy "Syncla-X [Mac AU]/Syncla-X Presets/Bass.aupreset", "{{user}}/Library/Audio/Plug-Ins/Components/Syncla-X Presets/Bass.aupreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Syncla-X Presets"
    copy "Syncla-X [Mac AU]/Syncla-X Presets/Bells.aupreset", "{{user}}/Library/Audio/Plug-Ins/Components/Syncla-X Presets/Bells.aupreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Syncla-X Presets"
    copy "Syncla-X [Mac AU]/Syncla-X Presets/Bells_2.aupreset", "{{user}}/Library/Audio/Plug-Ins/Components/Syncla-X Presets/Bells_2.aupreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Syncla-X Presets"
    copy "Syncla-X [Mac AU]/Syncla-X Presets/FM_Synth.aupreset", "{{user}}/Library/Audio/Plug-Ins/Components/Syncla-X Presets/FM_Synth.aupreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Syncla-X Presets"
    copy "Syncla-X [Mac AU]/Syncla-X Presets/Gong.aupreset", "{{user}}/Library/Audio/Plug-Ins/Components/Syncla-X Presets/Gong.aupreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Syncla-X Presets"
    copy "Syncla-X [Mac AU]/Syncla-X Presets/Harmonic_Pad.aupreset", "{{user}}/Library/Audio/Plug-Ins/Components/Syncla-X Presets/Harmonic_Pad.aupreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Syncla-X Presets"
    copy "Syncla-X [Mac AU]/Syncla-X Presets/Patch__10.aupreset", "{{user}}/Library/Audio/Plug-Ins/Components/Syncla-X Presets/Patch__10.aupreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Syncla-X Presets"
    copy "Syncla-X [Mac AU]/Syncla-X Presets/Patch__11.aupreset", "{{user}}/Library/Audio/Plug-Ins/Components/Syncla-X Presets/Patch__11.aupreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Syncla-X Presets"
    copy "Syncla-X [Mac AU]/Syncla-X Presets/Patch__12.aupreset", "{{user}}/Library/Audio/Plug-Ins/Components/Syncla-X Presets/Patch__12.aupreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Syncla-X Presets"
    copy "Syncla-X [Mac AU]/Syncla-X Presets/Patch__13.aupreset", "{{user}}/Library/Audio/Plug-Ins/Components/Syncla-X Presets/Patch__13.aupreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Syncla-X Presets"
    copy "Syncla-X [Mac AU]/Syncla-X Presets/Patch__14.aupreset", "{{user}}/Library/Audio/Plug-Ins/Components/Syncla-X Presets/Patch__14.aupreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Syncla-X Presets"
    copy "Syncla-X [Mac AU]/Syncla-X Presets/Patch__15.aupreset", "{{user}}/Library/Audio/Plug-Ins/Components/Syncla-X Presets/Patch__15.aupreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Syncla-X Presets"
    copy "Syncla-X [Mac AU]/Syncla-X Presets/Patch__16.aupreset", "{{user}}/Library/Audio/Plug-Ins/Components/Syncla-X Presets/Patch__16.aupreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Syncla-X Presets"
    copy "Syncla-X [Mac AU]/Syncla-X Presets/PSS_170_Honky_Piano.aupreset", "{{user}}/Library/Audio/Plug-Ins/Components/Syncla-X Presets/PSS_170_Honky_Piano.aupreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Syncla-X Presets"
    copy "Syncla-X [Mac AU]/Syncla-X Presets/Sines.aupreset", "{{user}}/Library/Audio/Plug-Ins/Components/Syncla-X Presets/Sines.aupreset"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Syncla-X Presets"
    copy "Syncla-X [Mac AU]/Syncla-X Presets/Steam_Organ.aupreset", "{{user}}/Library/Audio/Plug-Ins/Components/Syncla-X Presets/Steam_Organ.aupreset"
  end
end
