cask "transformant" do
  version "1.1.0"
  sha256 "0bf173764b09636fa01b15cc009bea14cf4dde5d3fb681a4255559e764a2b56c"
  url "https://github.com/igorski/transformant/releases/download/1.1.0/transformant.1.1.0_macos.zip"
  name "transformant"
  desc "Free audio plugin"
  homepage "https://github.com/igorski/transformant"
  depends_on :macos
  postflight_steps do
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3"
    move "AU/Transformant AUV3.app/Contents/PlugIns/auv3.appex/Contents/PlugIns/plugin.vst3", "{{user}}/Library/Audio/Plug-Ins/VST3/plugin.vst3"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST"
    move "VST/transformant.vst", "{{user}}/Library/Audio/Plug-Ins/VST/transformant.vst"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST3"
    move "VST3/transformant.vst3", "{{user}}/Library/Audio/Plug-Ins/VST3/transformant.vst3"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Transformant AUV3.app/Contents"
    copy "AU/Transformant AUV3.app/Contents/CodeResources", "{{user}}/Library/Audio/Plug-Ins/Components/Transformant AUV3.app/Contents/CodeResources"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Transformant AUV3.app/Contents"
    copy "AU/Transformant AUV3.app/Contents/Info.plist", "{{user}}/Library/Audio/Plug-Ins/Components/Transformant AUV3.app/Contents/Info.plist"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Transformant AUV3.app/Contents"
    copy "AU/Transformant AUV3.app/Contents/PkgInfo", "{{user}}/Library/Audio/Plug-Ins/Components/Transformant AUV3.app/Contents/PkgInfo"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Transformant AUV3.app/Contents/_CodeSignature"
    copy "AU/Transformant AUV3.app/Contents/_CodeSignature/CodeResources", "{{user}}/Library/Audio/Plug-Ins/Components/Transformant AUV3.app/Contents/_CodeSignature/CodeResources"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Transformant AUV3.app/Contents/MacOS"
    copy "AU/Transformant AUV3.app/Contents/MacOS/Transformant AUV3", "{{user}}/Library/Audio/Plug-Ins/Components/Transformant AUV3.app/Contents/MacOS/Transformant AUV3"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Transformant AUV3.app/Contents/Resources"
    copy "AU/Transformant AUV3.app/Contents/Resources/loop.wav", "{{user}}/Library/Audio/Plug-Ins/Components/Transformant AUV3.app/Contents/Resources/loop.wav"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Transformant AUV3.app/Contents/Resources"
    copy "AU/Transformant AUV3.app/Contents/Resources/plugin.icns", "{{user}}/Library/Audio/Plug-Ins/Components/Transformant AUV3.app/Contents/Resources/plugin.icns"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Transformant AUV3.app/Contents/Resources/Main.storyboardc"
    copy "AU/Transformant AUV3.app/Contents/Resources/Main.storyboardc/MainMenu.nib", "{{user}}/Library/Audio/Plug-Ins/Components/Transformant AUV3.app/Contents/Resources/Main.storyboardc/MainMenu.nib"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Transformant AUV3.app/Contents/Resources/Main.storyboardc"
    copy "AU/Transformant AUV3.app/Contents/Resources/Main.storyboardc/XfG-lQ-9wD-view-m2S-Jp-Qdl.nib", "{{user}}/Library/Audio/Plug-Ins/Components/Transformant AUV3.app/Contents/Resources/Main.storyboardc/XfG-lQ-9wD-view-m2S-Jp-Qdl.nib"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Transformant AUV3.app/Contents/Resources/Main.storyboardc"
    copy "AU/Transformant AUV3.app/Contents/Resources/Main.storyboardc/NSWindowController-B8D-0N-5wS.nib", "{{user}}/Library/Audio/Plug-Ins/Components/Transformant AUV3.app/Contents/Resources/Main.storyboardc/NSWindowController-B8D-0N-5wS.nib"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Transformant AUV3.app/Contents/Resources/Main.storyboardc"
    copy "AU/Transformant AUV3.app/Contents/Resources/Main.storyboardc/Info.plist", "{{user}}/Library/Audio/Plug-Ins/Components/Transformant AUV3.app/Contents/Resources/Main.storyboardc/Info.plist"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Transformant AUV3.app/Contents/PlugIns/auv3.appex/Contents"
    copy "AU/Transformant AUV3.app/Contents/PlugIns/auv3.appex/Contents/Info.plist", "{{user}}/Library/Audio/Plug-Ins/Components/Transformant AUV3.app/Contents/PlugIns/auv3.appex/Contents/Info.plist"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Transformant AUV3.app/Contents/PlugIns/auv3.appex/Contents/_CodeSignature"
    copy "AU/Transformant AUV3.app/Contents/PlugIns/auv3.appex/Contents/_CodeSignature/CodeResources", "{{user}}/Library/Audio/Plug-Ins/Components/Transformant AUV3.app/Contents/PlugIns/auv3.appex/Contents/_CodeSignature/CodeResources"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/Transformant AUV3.app/Contents/PlugIns/auv3.appex/Contents/MacOS"
    copy "AU/Transformant AUV3.app/Contents/PlugIns/auv3.appex/Contents/MacOS/transformant_auv3_appextension_macos", "{{user}}/Library/Audio/Plug-Ins/Components/Transformant AUV3.app/Contents/PlugIns/auv3.appex/Contents/MacOS/transformant_auv3_appextension_macos"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Resources"
    copy "README.txt", "{{user}}/Library/Audio/Plug-Ins/Resources/README.txt"
  end
end
