cask "vst-speek-vst" do
  version "latest"
  sha256 :no_check
  url "https://alt1.plugins4free.com/get_plug/VstSpeek3-MacVST.zip"
  name "VST Speek"
  desc "VST Speek is a speech software synthesizer : it reads the text you type in the text field."
  homepage "https://plugins4free.com/plugin/1863"
  depends_on :macos
  postflight_steps do
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST"
    move "VstSpeek3-x64.vst", "{{user}}/Library/Audio/Plug-Ins/VST/VstSpeek3-x64.vst"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/VstSpeek3.vst/__MACOSX"
    copy "VstSpeek3.vst/__MACOSX/._VstSpeek3.vst", "{{user}}/Library/Audio/Plug-Ins/VST/VstSpeek3.vst/__MACOSX/._VstSpeek3.vst"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/VstSpeek3.vst/__MACOSX/VstSpeek3.vst"
    copy "VstSpeek3.vst/__MACOSX/VstSpeek3.vst/._.DS_Store", "{{user}}/Library/Audio/Plug-Ins/VST/VstSpeek3.vst/__MACOSX/VstSpeek3.vst/._.DS_Store"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/VstSpeek3.vst/__MACOSX/VstSpeek3.vst"
    copy "VstSpeek3.vst/__MACOSX/VstSpeek3.vst/._Icon", "{{user}}/Library/Audio/Plug-Ins/VST/VstSpeek3.vst/__MACOSX/VstSpeek3.vst/._Icon"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/VstSpeek3.vst/VstSpeek3.vst"
    copy "VstSpeek3.vst/VstSpeek3.vst/.DS_Store", "{{user}}/Library/Audio/Plug-Ins/VST/VstSpeek3.vst/VstSpeek3.vst/.DS_Store"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/VstSpeek3.vst/VstSpeek3.vst/Contents/Frameworks/QtCore.framework/Versions/4"
    copy "VstSpeek3.vst/VstSpeek3.vst/Contents/Frameworks/QtCore.framework/Versions/4/QtCore", "{{user}}/Library/Audio/Plug-Ins/VST/VstSpeek3.vst/VstSpeek3.vst/Contents/Frameworks/QtCore.framework/Versions/4/QtCore"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/VstSpeek3.vst/VstSpeek3.vst/Contents/Frameworks/QtGui.framework/Resources/qt_menu.nib"
    copy "VstSpeek3.vst/VstSpeek3.vst/Contents/Frameworks/QtGui.framework/Resources/qt_menu.nib/classes.nib", "{{user}}/Library/Audio/Plug-Ins/VST/VstSpeek3.vst/VstSpeek3.vst/Contents/Frameworks/QtGui.framework/Resources/qt_menu.nib/classes.nib"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/VstSpeek3.vst/VstSpeek3.vst/Contents/Frameworks/QtGui.framework/Resources/qt_menu.nib"
    copy "VstSpeek3.vst/VstSpeek3.vst/Contents/Frameworks/QtGui.framework/Resources/qt_menu.nib/info.nib", "{{user}}/Library/Audio/Plug-Ins/VST/VstSpeek3.vst/VstSpeek3.vst/Contents/Frameworks/QtGui.framework/Resources/qt_menu.nib/info.nib"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/VstSpeek3.vst/VstSpeek3.vst/Contents/Frameworks/QtGui.framework/Resources/qt_menu.nib"
    copy "VstSpeek3.vst/VstSpeek3.vst/Contents/Frameworks/QtGui.framework/Resources/qt_menu.nib/keyedobjects.nib", "{{user}}/Library/Audio/Plug-Ins/VST/VstSpeek3.vst/VstSpeek3.vst/Contents/Frameworks/QtGui.framework/Resources/qt_menu.nib/keyedobjects.nib"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/VstSpeek3.vst/VstSpeek3.vst/Contents/Frameworks/QtGui.framework/Versions/4"
    copy "VstSpeek3.vst/VstSpeek3.vst/Contents/Frameworks/QtGui.framework/Versions/4/QtGui", "{{user}}/Library/Audio/Plug-Ins/VST/VstSpeek3.vst/VstSpeek3.vst/Contents/Frameworks/QtGui.framework/Versions/4/QtGui"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/VstSpeek3.vst/VstSpeek3.vst/Contents"
    copy "VstSpeek3.vst/VstSpeek3.vst/Contents/Info.plist", "{{user}}/Library/Audio/Plug-Ins/VST/VstSpeek3.vst/VstSpeek3.vst/Contents/Info.plist"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/VstSpeek3.vst/VstSpeek3.vst/Contents/MacOS"
    copy "VstSpeek3.vst/VstSpeek3.vst/Contents/MacOS/VstSpeek3", "{{user}}/Library/Audio/Plug-Ins/VST/VstSpeek3.vst/VstSpeek3.vst/Contents/MacOS/VstSpeek3"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/VstSpeek3.vst/VstSpeek3.vst/Contents"
    copy "VstSpeek3.vst/VstSpeek3.vst/Contents/PkgInfo", "{{user}}/Library/Audio/Plug-Ins/VST/VstSpeek3.vst/VstSpeek3.vst/Contents/PkgInfo"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/VST/VstSpeek3.vst/VstSpeek3.vst"
    copy "VstSpeek3.vst/VstSpeek3.vst/Icon", "{{user}}/Library/Audio/Plug-Ins/VST/VstSpeek3.vst/VstSpeek3.vst/Icon"
  end
end
