cask "world-stringz-au" do
  version "latest"
  sha256 :no_check
  url "https://alt1.plugins4free.com/get_plug/DSK_World_StringZ_AU.zip"
  name "World StringZ"
  desc "13 world string instruments : Celtic harp, Cumbus, Dobro, Dulcimer, Guzhen, Kanum, Koto, Luam, Pipa, Pipa tremolo, Sitar, Tar & Turkish Oud."
  homepage "https://plugins4free.com/plugin/1085"
  depends_on :macos
  postflight_steps do
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components"
    move "DSK World StringZ/DSK World Stringz.component", "{{user}}/Library/Audio/Plug-Ins/Components/DSK World Stringz.component"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/DSK World Stringz.instruments"
    copy "DSK World StringZ/DSK World Stringz.instruments/01 Celtic harp.mse", "{{user}}/Library/Audio/Plug-Ins/Components/DSK World Stringz.instruments/01 Celtic harp.mse"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/DSK World Stringz.instruments"
    copy "DSK World StringZ/DSK World Stringz.instruments/02 Cumbus.mse", "{{user}}/Library/Audio/Plug-Ins/Components/DSK World Stringz.instruments/02 Cumbus.mse"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/DSK World Stringz.instruments"
    copy "DSK World StringZ/DSK World Stringz.instruments/03 Dobro.mse", "{{user}}/Library/Audio/Plug-Ins/Components/DSK World Stringz.instruments/03 Dobro.mse"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/DSK World Stringz.instruments"
    copy "DSK World StringZ/DSK World Stringz.instruments/04 Dulcimer.mse", "{{user}}/Library/Audio/Plug-Ins/Components/DSK World Stringz.instruments/04 Dulcimer.mse"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/DSK World Stringz.instruments"
    copy "DSK World StringZ/DSK World Stringz.instruments/05 Guzhen.mse", "{{user}}/Library/Audio/Plug-Ins/Components/DSK World Stringz.instruments/05 Guzhen.mse"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/DSK World Stringz.instruments"
    copy "DSK World StringZ/DSK World Stringz.instruments/06 Kanum.mse", "{{user}}/Library/Audio/Plug-Ins/Components/DSK World Stringz.instruments/06 Kanum.mse"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/DSK World Stringz.instruments"
    copy "DSK World StringZ/DSK World Stringz.instruments/07 Koto.mse", "{{user}}/Library/Audio/Plug-Ins/Components/DSK World Stringz.instruments/07 Koto.mse"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/DSK World Stringz.instruments"
    copy "DSK World StringZ/DSK World Stringz.instruments/08 Luan.mse", "{{user}}/Library/Audio/Plug-Ins/Components/DSK World Stringz.instruments/08 Luan.mse"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/DSK World Stringz.instruments"
    copy "DSK World StringZ/DSK World Stringz.instruments/09 Pipa.mse", "{{user}}/Library/Audio/Plug-Ins/Components/DSK World Stringz.instruments/09 Pipa.mse"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/DSK World Stringz.instruments"
    copy "DSK World StringZ/DSK World Stringz.instruments/10 Pipa tremolo.mse", "{{user}}/Library/Audio/Plug-Ins/Components/DSK World Stringz.instruments/10 Pipa tremolo.mse"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/DSK World Stringz.instruments"
    copy "DSK World StringZ/DSK World Stringz.instruments/11 Sitar.mse", "{{user}}/Library/Audio/Plug-Ins/Components/DSK World Stringz.instruments/11 Sitar.mse"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/DSK World Stringz.instruments"
    copy "DSK World StringZ/DSK World Stringz.instruments/12 Tar.mse", "{{user}}/Library/Audio/Plug-Ins/Components/DSK World Stringz.instruments/12 Tar.mse"
    mkdir_p "{{user}}/Library/Audio/Plug-Ins/Components/DSK World Stringz.instruments"
    copy "DSK World StringZ/DSK World Stringz.instruments/13 Turkish oud.mse", "{{user}}/Library/Audio/Plug-Ins/Components/DSK World Stringz.instruments/13 Turkish oud.mse"
  end
end
